<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.ocean</groupId>
    <artifactId>OBDAHandler</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>OBDAHandler</name>
    <description>OBDAHandler</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>26</java.version>
        <owlapi.version>5.1.20</owlapi.version>
        <ontop.version>5.5.0</ontop.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-rdf4j</artifactId>
            <version>${ontop.version}</version>
        </dependency>
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-rdf4j</artifactId>
            <version>${ontop.version}</version>
        </dependency>
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-owlapi</artifactId>
            <version>${ontop.version}</version>
        </dependency>
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-mapping-r2rml</artifactId>
            <version>${ontop.version}</version>
        </dependency>
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-mapping-owlapi</artifactId>
            <version>${ontop.version}</version>
        </dependency>
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-system-core</artifactId>
            <version>${ontop.version}</version>
        </dependency>
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-system-sql-owlapi</artifactId>
            <version>${ontop.version}</version>
        </dependency>

        <!-- SQL + OWL API 映射配置模块（包含 OntopSQLOWLAPIConfiguration） -->
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-mapping-sql-owlapi</artifactId>
            <version>${ontop.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.rdf4j</groupId>
            <artifactId>rdf4j-repository-api</artifactId>
            <version>6.0.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.rdf4j</groupId>
            <artifactId>rdf4j-repository-sparql</artifactId>
            <version>6.0.0</version> <!-- 请确保与你的 RDF4J 其他模块版本一致 -->
        </dependency>
        <dependency>
            <groupId>it.unibz.inf.ontop</groupId>
            <artifactId>ontop-mapping-sql-core</artifactId>
            <version>5.5.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
