# -*- coding: utf-8 -*-
"""
症状 SKOS 词表数据（胡希恕·张仲景 经方视角）
键 = tcm-zhengzhuang.owl 中的类/个体 fragment（不含 _instance 后缀）
值 = dict(alt=[经方/文言同义词], hid=[白话/口语], definition=定义, note=伤寒论/金匮/胡老按语)
"""

SYN = {}

# ========== 一、寒热类 ==========
SYN["Fare"] = dict(
    alt=["发烧", "壮热", "身大热", "翕翕发热", "蒸蒸发热", "身灼热"],
    hid=["烧", "发烫", "体温高", "有点烧", "身上烫", "发烧了", "发热了", "体温37度以上"],
    definition="体温升高，或自觉身热。为正气抗邪之反应，六经皆有发热，须辨其热型与兼证。",
    note="伤寒论第3条：'太阳病，或已发热，或未发热，必恶寒。'胡老：发热恶寒发于阳，无热恶寒发于阴。")
SYN["Ere"] = dict(
    alt=["怕热", "畏热", "不耐热", "身畏热"],
    hid=["热得慌", "不喜欢热", "一热就烦", "嫌热", "讨厌热"],
    definition="自觉怕热、不耐热。阳明里热炽盛之特异性指征，与太阳表证之恶寒相对。",
    note="伤寒论第182条：'身热，汗自出，不恶寒，反恶热也。'胡老：此为里热之确据。")
SYN["Ehan"] = dict(
    alt=["恶风寒", "憎寒", "畏寒", "寒战", "洒淅恶寒", "啬啬恶寒"],
    hid=["怕冷", "发冷", "打寒战", "觉得冷", "冻得慌", "盖被子也冷", "冷战", "浑身发冷", "冷得发抖"],
    definition="自觉怕冷，加衣被不减。太阳表证或少阴里虚寒均可见。",
    note="伤寒论第7条：'病有发热恶寒者，发于阳也；无热恶寒者，发于阴也。'胡老：太阳之恶寒与发热并见，少阴之恶寒不发热而但欲寐。")
SYN["Efeng"] = dict(
    alt=["畏风", "恶风怕冷", "不耐风", "淅淅恶风"],
    hid=["怕风", "怕吹风", "见风冷", "不喜欢风", "避风", "一吹风就不舒服", "吹风就冷"],
    definition="自觉怕风，遇风则冷，避风则缓。太阳中风证（表虚证）特异性指征。",
    note="伤寒论第12条：'太阳中风……淅淅恶风。'胡老：恶风为太阳中风（表虚）之主症。")
SYN["Weihan"] = dict(
    alt=["微恶风寒", "恶寒轻"],
    hid=["有点怕冷", "稍微怕冷", "略怕冷"],
    definition="恶寒之轻者。见于表证轻浅或柴胡桂枝汤证。",
    note="伤寒论第146条：'伤寒六七日，发热微恶寒，支节烦疼……柴胡桂枝汤主之。'")
SYN["Beiehan"] = dict(
    alt=["背恶风寒"],
    hid=["后背怕冷", "背上发冷", "后背凉"],
    definition="背部自觉恶寒。多属阳虚，或痰饮内停、阳气不布。",
    note="伤寒论第304条：'少阴病，得之一二日，口中和，其背恶寒者，当灸之，附子汤主之。'")
SYN["Beihanleng"] = dict(
    alt=["背冷"],
    hid=["背冷", "后背冰凉", "背上凉飕飕"],
    definition="背部寒冷，触之亦冷。阳虚寒盛或水饮停聚之征。",
    note="金匮要略·痰饮：'夫心下有留饮，其人背寒冷如手大。'")
SYN["Shenhan"] = dict(
    alt=["身冷", "身体发冷"],
    hid=["身上冷", "浑身凉", "全身发冷"],
    definition="身体触之发冷，为客观之寒，与主观恶寒有别。多属阳虚阴盛。",
    note="胡老：身寒为阳气不足、不能温煦之候，与恶寒之自觉症不同。")
SYN["Mujifare"] = dict(
    alt=["暮发热"],
    hid=["傍晚发热", "晚上发烧"],
    definition="傍晚时分发热。多属阴虚或瘀血内结。",
    note="金匮要略·血痹虚劳：'暮即发热'属虚劳，宜温经补虚。")
SYN["Danrebuhan"] = dict(
    alt=["但热"],
    hid=["只热不冷", "光热不冷"],
    definition="但发热而不恶寒。阳明里热之候。",
    note="伤寒论第182条：'不恶寒，反恶热'即此。")
SYN["Chaore"] = dict(
    alt=["日晡潮热", "日晡发热", "日晡所发潮热"],
    hid=["下午发烧", "到点就烧", "傍晚热", "定时发热", "午后发热"],
    definition="热势如潮，定时而发（日晡所，即申时前后）。阳明腑实典型热型。",
    note="伤寒论第208条。胡老：日晡所潮热，属阳明，宜承气汤。")
SYN["Wanglaihanre"] = dict(
    alt=["寒热往来", "休作有时", "寒热交作", "寒热交争"],
    hid=["忽冷忽热", "一会冷一会热", "冷热交替", "打摆子", "一阵冷一阵热", "时冷时热"],
    definition="寒热交替发作，正邪分争，有明确时序交替特征。少阳病特异性热型。",
    note="伤寒论第96条。胡老：往来寒热为少阳病独有热型，小柴胡汤主之。")
SYN["Shenre"] = dict(
    alt=["身大热", "肌肤灼热"],
    hid=["浑身烫", "烧得厉害", "滚烫", "全身发热"],
    definition="身体灼热，但热不寒。阳明里热蒸腾于外。",
    note="伤寒论第182条。白虎汤证四大症之一。")
SYN["Shenrebuqu"] = dict(
    alt=["身热不退"],
    hid=["一直发烧", "烧退不下来", "持续发热"],
    definition="身热持续不去。多属湿热留恋或里热未清。",
    note="伤寒论第63条：'发汗后，不可更行桂枝汤，汗出而喘，无大热者……'")
SYN["Dare"] = dict(
    alt=["大热", "壮热"],
    hid=["高烧", "烧得很高", "热得厉害"],
    definition="热势炽盛。阳明里热亢盛之候。",
    note="胡老：大热为阳明经热，白虎汤主之。")
SYN["Sasaehan"] = dict(
    alt=["洒淅恶寒", "啬啬恶寒"],
    hid=["一阵阵发冷", "冷飕飕"],
    definition="如冷水洒身之恶寒，阵阵发作。太阳表证之恶寒貌。",
    note="伤寒论第12条：'啬啬恶寒，淅淅恶风'，桂枝汤证。")
SYN["Shishifare"] = dict(
    alt=["时时发热"],
    hid=["一阵阵发热", "时不时发烧"],
    definition="发热时作时止。多属表证未解或正邪交争。",
    note="伤寒论第48条。")
SYN["Wuhanre"] = dict(
    alt=["无寒热"],
    hid=["不冷不热", "没有寒热"],
    definition="既不畏寒亦不发热。多见于里证或病在血分。",
    note="金匮要略·妇人杂病：'妇人宿有癥病……所以血不止者，其癥不去故也。'")
SYN["Shenwure"] = dict(
    alt=["身无热"],
    hid=["身上不热", "体温正常"],
    definition="身体无发热。",
    note="")
SYN["Mianyourese"] = dict(
    alt=["面有热色"],
    hid=["脸上发红发热", "脸发烫"],
    definition="面部呈现热色。表郁轻证，阳气怫郁在表。",
    note="伤寒论第23条：'面色反有热色者，未欲解也，以其不能得小汗出，身必痒，宜桂枝麻黄各半汤。'")
SYN["Reduohanshao"] = dict(
    alt=["热多寒少"],
    hid=["热多冷少"],
    definition="发热多而恶寒少。表证渐解，正气渐复。",
    note="伤寒论第23条：'太阳病，得之八九日，如疟状，发热恶寒，热多寒少。'")
SYN["Handuoreshao"] = dict(
    alt=["寒多热少"],
    hid=["冷多热少"],
    definition="恶寒多而发热少。阳虚寒盛之候。",
    note="伤寒论第23条。")
SYN["Runvezhuang"] = dict(
    alt=["如疟"],
    hid=["像打摆子", "像疟疾一样"],
    definition="寒热发作如疟疾之状。",
    note="伤寒论第23条：'如疟状，发热恶寒。'")
SYN["Yirizaifa"] = dict(
    alt=["一日再发"],
    hid=["一天发作两次"],
    definition="一日发作两次。表郁轻证之热型。",
    note="伤寒论第23条：'一日再发者，汗出必解，宜桂枝二麻黄一汤。'")
SYN["Shendahan"] = dict(
    alt=["身大寒"],
    hid=["浑身冰冷", "全身发冷得厉害"],
    definition="身体大寒。阴寒内盛，阳气衰微之危候。",
    note="伤寒论第11条：'身大寒，反不欲近衣者，寒在皮肤，热在骨髓也。'")
SYN["Wureehan"] = dict(
    alt=["无热恶寒"],
    hid=["不发烧但怕冷", "光冷"],
    definition="不发热而但恶寒。病发于阴，多属少阴、太阴。",
    note="伤寒论第7条：'无热恶寒者，发于阴也。'胡老：此属少阴。")
SYN["Xixifare"] = dict(
    alt=["翕翕发热"],
    hid=["微微发热", "身上温热"],
    definition="发热如羽毛覆盖之轻浅状。太阳中风之发热貌。",
    note="伤寒论第12条：'翕翕发热，鼻鸣干呕者，桂枝汤主之。'")
SYN["Zhengzhengfare"] = dict(
    alt=["蒸蒸发热"],
    hid=["蒸蒸地热", "一阵阵热得冒汗"],
    definition="发热如蒸笼之状，热自内蒸。阳明里热之候。",
    note="伤寒论第248条：'太阳病三日，发汗不解，蒸蒸发热者，属胃也，调胃承气汤主之。'")
SYN["Ribusuofare"] = dict(
    alt=["日晡发热"],
    hid=["下午发热", "傍晚发烧"],
    definition="日晡（申时）发热。阳明腑实之热型。",
    note="伤寒论第240条。")
SYN["Buehan"] = dict(
    alt=["不恶寒"],
    hid=["不怕冷"],
    definition="不畏寒。里热之征，或表证已解。",
    note="伤寒论第182条：'不恶寒，反恶热。'")
SYN["Shouzuwen"] = dict(
    alt=["手足温"],
    hid=["手脚温热", "手脚暖和"],
    definition="手足温暖。阳气尚能达于四末，病势较轻。",
    note="伤寒论第287条：'少阴病，脉紧，至七八日，自下利，脉暴微，手足反温，脉紧反去者，为欲解也。'")
SYN["Fanre"] = dict(
    alt=["烦热"],
    hid=["又烦又热", "心里烦身上热"],
    definition="发热而兼心烦。里热扰心之候。",
    note="伤寒论第77条：'发汗若下之，而烦热胸中窒者，栀子豉汤主之。'")
SYN["Touxiangqiangtong"] = dict(
    alt=["头项强痛", "项强痛"],
    hid=["脖子僵硬头疼", "后脑勺疼脖子硬"],
    definition="头痛兼项部强直疼痛。太阳病提纲证之一。",
    note="伤寒论第1条：'太阳之为病，脉浮，头项强痛而恶寒。'")
SYN["Wudare"] = dict(
    alt=["无大热"],
    hid=["不太烧", "没有高烧"],
    definition="无高热。表邪未尽或热已内陷之候。",
    note="伤寒论第63条：'汗出而喘，无大热者，可与麻黄杏仁甘草石膏汤。'")
SYN["Weire"] = dict(
    alt=["微热", "低热"],
    hid=["低烧", "有点热", "微微发烧"],
    definition="发热轻微。表邪轻浅或阴虚内热。",
    note="伤寒论第252条：'伤寒六七日，目中不了了……身微热者，此为实也。'")
SYN["Shenzhuore"] = dict(
    alt=["身灼热"],
    hid=["身上滚烫", "浑身灼热"],
    definition="身体灼热如焚。阳明热盛或温病热入营血。",
    note="伤寒论第6条：'太阳病，发热而渴，不恶寒者，为温病。'")
SYN["Yudebeifuxianghuo"] = dict(
    alt=["欲近衣被", "向火"],
    hid=["想盖被子", "想烤火", "想靠近暖气"],
    definition="欲得衣被覆盖、向火取暖。里虚寒之征。",
    note="伤寒论第11条：'身大热，反欲得近衣者，热在皮肤，寒在骨髓也。'")
SYN["Xiaoyoulaoshenjire"] = dict(
    alt=["劳则发热"],
    hid=["一累就发热", "稍一活动就热"],
    definition="稍事劳作即发热。气虚或虚劳之候。",
    note="金匮要略·血痹虚劳：'小有劳，身即热。'")
SYN["Zhenhan"] = dict(
    alt=["振寒", "寒战"],
    hid=["打寒战", "发抖发冷", "冷得哆嗦"],
    definition="身体振颤而寒。正邪交争或阳虚之候。",
    note="伤寒论第94条：'太阳病未解，脉阴阳俱停，必先振栗汗出而解。'")

# ========== 二、汗出类 ==========
SYN["Hanchu"] = dict(
    alt=["出汗", "有汗", "汗自出", "微汗出", "自汗出"],
    hid=["流汗", "冒汗", "一身汗", "虚汗", "出汗不止", "老出汗"],
    definition="体表有汗液排出。表证汗出为中风（桂枝汤证）。",
    note="伤寒论第12条：'阴弱者汗自出。'胡老：病汗与药汗有别。")
SYN["Wuhan"] = dict(
    alt=["不出汗", "汗不出", "无汗出"],
    hid=["没汗", "干烧", "皮肤干", "一滴汗都没有", "不出汗"],
    definition="体表干燥无汗。表实证标志，腠理闭塞。",
    note="伤寒论第35条：'无汗而喘'，麻黄汤证主症之一。")
SYN["Zihan"] = dict(
    alt=["常自汗出", "汗出不止"],
    hid=["出虚汗", "老出汗", "动不动就出汗", "自汗"],
    definition="不因劳作、天热而自然汗出。表虚或阳明里热迫津所致。",
    note="伤寒论第53条：'病常自汗出者，此为荣气和……以卫气不共荣气谐和故尔。'")
SYN["Daohan"] = dict(
    alt=["寝汗", "目合则汗"],
    hid=["夜里出汗", "睡觉出汗", "睡着出汗", "盗汗"],
    definition="睡中汗出，醒则汗止。阴虚或虚劳之候。",
    note="金匮要略·血痹虚劳：'男子平人，脉虚弱细微者，喜盗汗也。'")
SYN["Dantouhanchu"] = dict(
    alt=["但头汗出", "头汗"],
    hid=["只有头上出汗", "头出汗身上不出"],
    definition="仅头部汗出，齐颈而还。湿热郁蒸或阳气上越之候。",
    note="伤寒论第111条、第236条。胡老：但头汗出，多为湿热或阳脱。")
SYN["Huanghan"] = dict(
    alt=["黄汗出"],
    hid=["出黄汗", "汗是黄的", "汗沾衣"],
    definition="汗出色黄如柏汁，沾衣色黄。湿热交蒸之候。",
    note="金匮要略·水气病：'黄汗之为病，身体肿，发热汗出而渴，状如风水，汗沾衣，色正黄如柏汁。'")
SYN["Dahan"] = dict(
    alt=["大汗出", "汗大出"],
    hid=["大汗", "出很多汗", "汗如雨下", "浑身是汗"],
    definition="汗出量多。阳明热盛迫津，或阳气外脱。",
    note="伤寒论第26条：'服桂枝汤，大汗出后，大烦渴不解，脉洪大者，白虎加人参汤主之。'")
SYN["Duohanchu"] = dict(
    alt=["多汗"],
    hid=["汗多", "经常出汗", "动不动一身汗"],
    definition="经常性汗出过多，与大汗（急性）区分。",
    note="")
SYN["Muhezehan"] = dict(
    alt=["目合汗出"],
    hid=["一闭眼就出汗", "睡着了出汗"],
    definition="闭目则汗出。阴虚盗汗之甚者。",
    note="伤寒论第268条：'三阳合病……目合则汗。'")
SYN["Shouzujiranhanchu"] = dict(
    alt=["手足濈然汗出", "手足汗出"],
    hid=["手脚出汗", "手心脚心出汗"],
    definition="手足持续汗出。阳明腑实燥屎内结之征。",
    note="伤寒论第208条：'手足濈然汗出者，此大便已硬也，大承气汤主之。'")
SYN["Shiyihanchu"] = dict(
    alt=["食已汗出"],
    hid=["一吃饭就出汗", "吃饭出汗"],
    definition="进食后汗出。胃热或气虚之候。",
    note="金匮要略·血痹虚劳：'食已汗出，又身常暮卧盗汗出者，此劳气也。'")
SYN["Ruofazebaihanchu"] = dict(
    alt=["白汗出"],
    hid=["出冷汗", "冷汗"],
    definition="发作时出白色冷汗。阳虚寒盛之候。",
    note="金匮要略·腹满寒疝宿食：'若发则白汗出，手足厥冷。'")
SYN["Muchangdaohanchu"] = dict(
    alt=["暮常盗汗出"],
    hid=["晚上老出汗", "夜里常出汗"],
    definition="入暮常盗汗。虚劳之候。",
    note="金匮要略·血痹虚劳。")
SYN["Hanloubuzhi"] = dict(
    alt=["汗漏不止"],
    hid=["汗止不住", "一直出汗止不住"],
    definition="汗出如漏，持续不止。阳虚不固，卫外失司。",
    note="伤寒论第20条：'太阳病，发汗，遂漏不止，其人恶风，小便难，四肢微急，难以屈伸者，桂枝加附子汤主之。'")

# ========== 三、头面颈项类 ==========
SYN["Toutong"] = dict(
    alt=["头疼", "头痛", "首痛"],
    hid=["头疼", "脑袋疼", "头很痛", "头痛", "偏头痛"],
    definition="头部疼痛。六经皆有头痛，须辨部位与兼证。",
    note="伤寒论第1条：'头项强痛'。胡老：太阳头痛多在项背，少阳头痛多在两侧，阳明头痛多在前额。")
SYN["Touxuan"] = dict(
    alt=["头晕", "眩晕", "冒眩", "苦冒眩"],
    hid=["头晕", "眩晕", "天旋地转", "晕得厉害", "头昏"],
    definition="头目昏眩。多属痰饮上泛、清阳不升。",
    note="金匮要略·痰饮：'心下有支饮，其人苦冒眩，泽泻汤主之。'")
SYN["Qizetouxuan"] = dict(
    alt=["起则头眩"],
    hid=["一站起来就头晕", "起身头晕"],
    definition="起立时即感头眩。痰饮内停，清阳不升。",
    note="伤寒论第67条：'心下逆满，气上冲胸，起则头眩……茯苓桂枝白术甘草汤主之。'")
SYN["Muxuan"] = dict(
    alt=["目眩", "眼花"],
    hid=["眼花", "眼前发花", "看东西转"],
    definition="视物昏花旋转。少阳或痰饮之候。",
    note="伤寒论第263条：'少阳之为病，口苦，咽干，目眩也。'")
SYN["Muchi"] = dict(
    alt=["目赤", "眼红"],
    hid=["眼睛红", "眼白发红", "眼睛充血"],
    definition="目睛红赤。肝火或风热上攻。",
    note="伤寒论第263条。")
SYN["Muming"] = dict(
    alt=["目瞑", "闭目"],
    hid=["闭着眼睛", "不想睁眼"],
    definition="闭目不欲睁。多属阳虚或血虚。",
    note="伤寒论第46条：'其人发烦目瞑。'")
SYN["Muhuang"] = dict(
    alt=["目黄", "眼黄"],
    hid=["眼睛发黄", "眼白发黄"],
    definition="白睛发黄。黄疸之征。",
    note="金匮要略·黄疸病：'目黄者，曰黄疸。'")
SYN["Mianchi"] = dict(
    alt=["面赤", "面红", "面色赤"],
    hid=["脸发红", "脸红", "脸通红"],
    definition="面部红赤。阳明热盛或虚阳上浮。",
    note="伤寒论第48条：'阳气怫郁在表，当解之熏之。'")
SYN["Mianre"] = dict(
    alt=["面热"],
    hid=["脸发热", "脸上发烫"],
    definition="面部发热。阳明经热或虚阳上越。",
    note="伤寒论第206条：'阳明病，面合色赤。'")
SYN["Miangou"] = dict(
    alt=["面垢"],
    hid=["脸上像蒙了灰", "脸油腻发暗"],
    definition="面部如蒙尘垢。阳明热盛或中暑之候。",
    note="伤寒论第219条：'三阳合病……口不仁，面垢。'")
SYN["Mianseweihuang"] = dict(
    alt=["面色萎黄"],
    hid=["脸色发黄", "面黄无光", "脸色萎黄"],
    definition="面色黄而枯槁无华。脾胃虚弱、气血不足。",
    note="金匮要略·黄疸病。")
SYN["Mianfu"] = dict(
    alt=["面浮", "面肿"],
    hid=["脸肿", "脸浮肿", "脸发胀"],
    definition="面部浮肿。风水或阳虚水泛。",
    note="金匮要略·水气病：'面目肿大，有热，名曰风水。'")
SYN["Mianseqing"] = dict(
    alt=["面色青"],
    hid=["脸色发青", "脸青"],
    definition="面色发青。寒证、痛证、瘀血或惊风。",
    note="胡老：面青多主寒、主痛、主瘀。")
SYN["Miansebai"] = dict(
    alt=["面色白", "面白"],
    hid=["脸色苍白", "脸白", "面色发白"],
    definition="面色苍白。血虚或阳虚寒盛。",
    note="金匮要略·血痹虚劳：'男子面色薄者，主渴及亡血。'")
SYN["Eshanghei"] = dict(
    alt=["额上黑"],
    hid=["额头黑", "额头暗黑"],
    definition="额部色黑。女劳疸之候，肾虚夹瘀。",
    note="金匮要略·黄疸病：'额上黑，微汗出，手足中热……名曰女劳疸。'")
SYN["Mianchibanbanrujinwen"] = dict(
    alt=["面赤斑斑如锦纹"],
    hid=["脸上红斑如花纹", "脸上起红斑"],
    definition="面部红斑如锦缎花纹。阳毒之候。",
    note="金匮要略·百合狐惑阴阳毒：'阳毒之为病，面赤斑斑如锦纹。'")
SYN["Xiangqiang"] = dict(
    alt=["项强", "颈项强"],
    hid=["脖子僵硬", "脖子发硬", "后脖颈僵硬"],
    definition="项部强直不舒。太阳经气不利或痉病。",
    note="伤寒论第1条：'头项强痛'。")
SYN["Beiqiang"] = dict(
    alt=["背强"],
    hid=["后背僵硬", "背部发紧"],
    definition="背部强直。太阳经输不利。",
    note="伤寒论第31条：'太阳病，项背强几几，无汗恶风，葛根汤主之。'")
SYN["Xiangbeiqiangjiji"] = dict(
    alt=["项背强几几", "项背强"],
    hid=["脖子后背发紧僵硬", "后脖子到后背僵"],
    definition="项背拘紧不舒，如短羽鸟欲飞之状。太阳经输不利。",
    note="伤寒论第14条：'项背强几几，反汗出恶风者，桂枝加葛根汤主之。'")
SYN["Shentiqiangjiji"] = dict(
    alt=["身体强几几"],
    hid=["浑身发僵", "全身僵硬"],
    definition="身体拘紧强直。",
    note="金匮要略·痉湿暍病。")
SYN["Erlong"] = dict(
    alt=["耳聋", "重听"],
    hid=["耳朵听不见", "听不清", "耳背"],
    definition="听力减退或丧失。少阳经气不利或肾虚。",
    note="伤寒论第264条：'少阳中风，两耳无所闻。'")
SYN["Erqianhouzhong"] = dict(
    alt=["耳前后肿"],
    hid=["耳朵前后肿", "腮帮子肿"],
    definition="耳前耳后肿胀。少阳风热或痄腮。",
    note="伤寒论第231条：'耳前后肿，刺之小差。'")
SYN["Biming"] = dict(
    alt=["鼻鸣"],
    hid=["鼻子不通气有声", "鼻子呼呼响"],
    definition="鼻塞而呼吸有声。太阳中风之候。",
    note="伤寒论第12条：'鼻鸣干呕者，桂枝汤主之。'")
SYN["Binv"] = dict(
    alt=["鼻衄", "鼻出血"],
    hid=["流鼻血", "鼻子出血", "鼻子流血"],
    definition="鼻中出血。表热郁闭或阳明热盛迫血。",
    note="伤寒论第46条：'阳气重故也，麻黄汤主之。'胡老：衄乃解。")
SYN["Muzhongbulele"] = dict(
    alt=["目中不了了"],
    hid=["看东西不清楚", "眼睛发直看不清"],
    definition="视物模糊不清。阳明腑实、热灼津液之危候。",
    note="伤寒论第252条：'伤寒六七日，目中不了了，睛不和，无表里证，大便难，身微热者，此为实也，急下之，宜大承气汤。'")
SYN["Jingbuhe"] = dict(
    alt=["睛不和"],
    hid=["眼珠转动不灵", "眼睛发直"],
    definition="目睛转动不灵活。热盛津伤之危候。",
    note="伤寒论第252条。")
SYN["Murutuozhuang"] = dict(
    alt=["目如脱状"],
    hid=["眼睛像要掉出来", "眼珠外突"],
    definition="目睛胀突如脱。肺胀痰饮之候。",
    note="金匮要略·肺痿肺痈咳嗽上气：'咳而上气，此为肺胀……目如脱状，脉浮大者，越婢加半夏汤主之。'")
SYN["Mianselihei"] = dict(
    alt=["面色黧黑"],
    hid=["脸色发黑", "脸黑"],
    definition="面色黑而晦暗。肾虚或瘀血内停。",
    note="金匮要略·痰饮：'膈间支饮，其人喘满，心下痞坚，面色黧黑。'")
SYN["Muchirujiuyan"] = dict(
    alt=["目赤如鸠眼"],
    hid=["眼睛红得像斑鸠眼"],
    definition="目赤如斑鸠之眼。狐惑病之候。",
    note="金匮要略·百合狐惑阴阳毒：'目赤如鸠眼。'")
SYN["Touzhong"] = dict(
    alt=["头重"],
    hid=["头沉", "脑袋发沉", "头重脚轻"],
    definition="头部沉重。湿浊上蒙或清阳不升。",
    note="伤寒论第392条：'头重不欲举。'")
SYN["Muqizichu"] = dict(
    alt=["目泣自出"],
    hid=["眼泪自己流", "不自主流泪"],
    definition="眼泪不自主流出。",
    note="金匮要略·痰饮：'目泣自出。'")
SYN["Bigan"] = dict(
    alt=["鼻干"],
    hid=["鼻子干", "鼻腔干燥"],
    definition="鼻腔干燥。阳明热盛或肺燥。",
    note="伤寒论第227条：'脉浮发热，口干鼻燥，能食者则衄。'")
SYN["Muteng"] = dict(
    alt=["目疼", "眼痛"],
    hid=["眼睛疼", "眼珠子疼"],
    definition="眼目疼痛。肝火或风热。",
    note="伤寒论第263条。")
SYN["Murundong"] = dict(
    alt=["目瞤动"],
    hid=["眼皮跳", "眼睛跳"],
    definition="眼睑跳动。风动或血虚。",
    note="胡老：目瞤动多属血虚风动。")
SYN["Mukeshangweiyong"] = dict(
    alt=["目窠上微拥"],
    hid=["眼泡微肿", "眼皮肿"],
    definition="眼胞微肿。水气之候。",
    note="金匮要略·水气病：'目窠上微拥，如蚕新卧起状。'")
SYN["Muxiayouwocan"] = dict(
    alt=["目下有卧蚕"],
    hid=["眼下像卧蚕", "眼袋肿"],
    definition="下眼睑浮肿如卧蚕。水气之候。",
    note="金匮要略·水气病。")

# ========== 四、口咽类 ==========
SYN["Kouke"] = dict(
    alt=["口渴", "口干渴"],
    hid=["口渴", "口干", "想喝水", "嘴里干"],
    definition="口渴欲饮。里热伤津或水液不布。",
    note="伤寒论第71条：'太阳病，发汗后……胃中干，烦躁不得眠，欲得饮水者，少少与饮之。'")
SYN["Dake"] = dict(
    alt=["大渴", "大渴引饮"],
    hid=["非常渴", "渴得厉害", "狂喝水"],
    definition="口渴特甚，引饮不止。阳明热盛津伤。",
    note="伤寒论第26条：'大烦渴不解，脉洪大者，白虎加人参汤主之。'")
SYN["Buke"] = dict(
    alt=["不渴"],
    hid=["不口渴", "不想喝水"],
    definition="口不渴。里无热或津液未伤。",
    note="伤寒论第304条：'口中和'即不渴不苦。")
SYN["Fanbuke"] = dict(
    alt=["反不渴"],
    hid=["反而不渴"],
    definition="本当渴而反不渴。水饮内停或阴寒内盛。",
    note="金匮要略·痰饮：'夫心下有留饮，其人背寒冷如手大。'")
SYN["Yuyin"] = dict(
    alt=["欲饮水"],
    hid=["想喝水", "要喝水"],
    definition="欲饮水。里热或津伤。",
    note="伤寒论第71条。")
SYN["Buyuyin"] = dict(
    alt=["不欲饮", "不欲饮水"],
    hid=["不想喝水", "不爱喝水"],
    definition="不欲饮水。水饮内停或阴寒。",
    note="伤寒论第282条：'自利不渴者，属太阴。'")
SYN["Kouku"] = dict(
    alt=["口苦", "口苦咽干"],
    hid=["嘴里苦", "口苦", "嘴发苦"],
    definition="口中觉苦。少阳病提纲证之一，胆火上炎。",
    note="伤寒论第263条：'少阳之为病，口苦，咽干，目眩也。'胡老：口苦为少阳第一主症。")
SYN["Kouburen"] = dict(
    alt=["口不仁"],
    hid=["嘴麻木", "口唇麻木不知味"],
    definition="口部麻木，不知味觉。阳明热盛之候。",
    note="伤寒论第219条：'三阳合病……口不仁。'")
SYN["Kousheburen"] = dict(
    alt=["口舌不仁"],
    hid=["口舌麻木"],
    definition="口舌麻木不仁。",
    note="")
SYN["Koujin"] = dict(
    alt=["口噤", "牙关紧闭"],
    hid=["嘴张不开", "牙关紧闭"],
    definition="口不能开。痉病或热极动风。",
    note="金匮要略·痉湿暍病：'卒口噤，背反张者，痉病也。'")
SYN["Kousheganzao"] = dict(
    alt=["口舌干燥"],
    hid=["口舌都干", "嘴和舌头都干"],
    definition="口舌干燥。津液不足。",
    note="伤寒论第168条。")
SYN["Chunkouganzao"] = dict(
    alt=["唇口干燥"],
    hid=["嘴唇干", "嘴干唇裂"],
    definition="唇口干燥。津血不足或瘀血。",
    note="金匮要略·妇人杂病：'唇口干燥，温经汤主之。'")
SYN["Chunan"] = dict(
    alt=["唇暗", "唇色暗"],
    hid=["嘴唇发暗", "唇色发紫暗"],
    definition="口唇色暗。瘀血或寒凝。",
    note="胡老：唇暗多主瘀。")
SYN["Chunwei"] = dict(
    alt=["唇痿"],
    hid=["嘴唇萎缩", "嘴唇干瘪"],
    definition="口唇枯萎不泽。",
    note="金匮要略·血痹虚劳。")
SYN["Yangan"] = dict(
    alt=["咽干", "嗌干"],
    hid=["嗓子干", "喉咙干", "咽喉干燥"],
    definition="咽喉干燥。少阳热盛或津伤。",
    note="伤寒论第263条：'口苦，咽干，目眩。'")
SYN["Yantong"] = dict(
    alt=["咽痛", "喉痛"],
    hid=["嗓子疼", "喉咙痛", "咽口水都疼"],
    definition="咽喉疼痛。少阴客热或虚火上炎。",
    note="伤寒论第310条：'少阴病，下利，咽痛，胸满，心烦，猪肤汤主之。'")
SYN["Yanzhongtong"] = dict(
    alt=["咽中痛"],
    hid=["嗓子里面疼", "喉咙里面痛"],
    definition="咽中疼痛。",
    note="伤寒论第313条：'少阴病，咽中痛，半夏散及汤主之。'")
SYN["Yanhoubuli"] = dict(
    alt=["咽喉不利"],
    hid=["嗓子不舒服", "喉咙不利索"],
    definition="咽喉不利。痰气交阻或津伤。",
    note="金匮要略·肺痿肺痈咳嗽上气：'火逆上气，咽喉不利，止逆下气者，麦门冬汤主之。'")
SYN["Yanzhongruyouzhiluan"] = dict(
    alt=["咽中如有炙脔", "梅核气"],
    hid=["嗓子里像有东西堵着", "喉咙有异物感", "咽不下吐不出"],
    definition="咽中如有物阻，咯之不出、咽之不下。痰气交阻。",
    note="金匮要略·妇人杂病：'妇人咽中如有炙脔，半夏厚朴汤主之。'")
SYN["Danyushushuibuyuyan"] = dict(
    alt=["但欲漱水不欲咽"],
    hid=["只想漱口不想咽", "含水不咽"],
    definition="但欲漱水而不欲咽下。瘀血之候。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病：'病人胸满，唇痿舌青，口燥，但欲漱水不欲咽，无寒热……为有瘀血。'")
SYN["Danyuyinre"] = dict(
    alt=["但欲饮热"],
    hid=["只想喝热水", "爱喝热的"],
    definition="但欲饮热。里寒之候。",
    note="伤寒论第11条。")
SYN["Tunong"] = dict(
    alt=["吐脓"],
    hid=["吐脓", "咳吐脓痰"],
    definition="吐出脓液。肺痈之候。",
    note="金匮要略·肺痿肺痈咳嗽上气。")
SYN["Tunongxue"] = dict(
    alt=["吐脓血"],
    hid=["吐脓血", "咳吐脓血"],
    definition="吐出脓血。肺痈溃脓之候。",
    note="金匮要略·肺痿肺痈咳嗽上气：'咳而胸满，振寒脉数，咽干不渴，时出浊唾腥臭，久久吐脓如米粥者，为肺痈。'")
SYN["Tuxian"] = dict(
    alt=["吐涎"],
    hid=["吐口水", "流口水"],
    definition="口中涎液外吐。",
    note="金匮要略·痰饮。")
SYN["Tuxianmo"] = dict(
    alt=["吐涎沫"],
    hid=["吐白沫", "吐清稀口水"],
    definition="吐出清稀涎沫。肺痿或寒饮之候。",
    note="金匮要略·肺痿肺痈咳嗽上气：'肺痿吐涎沫而不咳者，其人不渴，必遗尿，小便数。'")
SYN["Tuzhuo"] = dict(
    alt=["吐浊"],
    hid=["吐浊痰", "吐黏痰"],
    definition="吐出浊痰。",
    note="金匮要略·肺痿肺痈咳嗽上气。")
SYN["Tuxue"] = dict(
    alt=["吐血"],
    hid=["吐血", "呕血"],
    definition="血从口出。胃热或肝火犯胃，或脾不统血。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病：'吐血不止者，柏叶汤主之。'")
SYN["Tuxuebuzhi"] = dict(
    alt=["吐血不止"],
    hid=["吐血止不住", "一直吐血"],
    definition="吐血持续不止。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病。")
SYN["Xiaoke"] = dict(
    alt=["消渴"],
    hid=["多饮多尿", "喝水多尿多", "消渴"],
    definition="口渴多饮而小便反多。津液耗伤、水不化气。",
    note="金匮要略·消渴小便不利淋病：'男子消渴，小便反多，以饮一斗，小便一斗，肾气丸主之。'")
SYN["Shuiruzetu"] = dict(
    alt=["水入则吐"],
    hid=["一喝水就吐", "喝水就吐出来"],
    definition="饮水即吐。水逆之候。",
    note="伤寒论第74条：'渴欲饮水，水入则吐者，名曰水逆，五苓散主之。'")
SYN["Tuhui"] = dict(
    alt=["吐蛔", "吐蛔虫"],
    hid=["吐蛔虫", "吐出虫子"],
    definition="吐出蛔虫。蛔厥之候。",
    note="伤寒论第338条：'蛔厥者，其人当吐蛔。'")
SYN["Kouzhonghe"] = dict(
    alt=["口中和"],
    hid=["嘴里没味", "口不苦不干"],
    definition="口中和，不苦不干不渴。里无热之征。",
    note="伤寒论第304条：'少阴病，得之一二日，口中和，其背恶寒者……附子汤主之。'")
SYN["Kouzao"] = dict(
    alt=["口燥", "口干"],
    hid=["口干", "嘴干", "口干舌燥"],
    definition="口中干燥。津液不足或热盛伤津。",
    note="伤寒论第202条：'口燥，但欲漱水不欲咽。'")
SYN["Butu"] = dict(
    alt=["不吐"],
    hid=["不吐", "没有呕吐"],
    definition="无呕吐。",
    note="")
SYN["Outubuzhi"] = dict(
    alt=["呕吐不止"],
    hid=["吐个不停", "一直吐"],
    definition="呕吐持续不止。",
    note="金匮要略·呕吐哕下利病：'干呕吐逆，吐涎沫，半夏干姜散主之。'")
SYN["Koushanglanchi"] = dict(
    alt=["口伤烂赤"],
    hid=["口舌溃烂发红"],
    definition="口腔溃烂红赤。",
    note="伤寒论第334条。")
SYN["Aigan"] = dict(
    alt=["嗌干"],
    hid=["咽喉干", "嗓子干痛"],
    definition="咽喉干燥。",
    note="伤寒论第320条：'少阴病，得之二三日，口燥咽干者，急下之。'")
SYN["Kouzhongpipizao"] = dict(
    alt=["口中辟辟燥"],
    hid=["嘴里干得厉害"],
    definition="口中干燥特甚。",
    note="金匮要略·肺痿肺痈咳嗽上气。")
SYN["Koukai"] = dict(
    alt=["口开"],
    hid=["嘴张开合不上", "张口不合"],
    definition="口开不合。中风脱证之危候。",
    note="金匮要略·中风历节病。")
SYN["Qianbanchizao"] = dict(
    alt=["前板齿燥"],
    hid=["门牙干燥", "前牙发干"],
    definition="门齿干燥。阳明热盛津伤之候。",
    note="伤寒论第6条：'若发汗已，身灼热者，名风温……以阴气为寒所迫，故前板齿燥。'")
SYN["Yanzhongshangshengchuang"] = dict(
    alt=["咽中伤生疮"],
    hid=["嗓子里生疮", "咽喉溃烂"],
    definition="咽喉损伤生疮。",
    note="伤寒论第312条：'少阴病，咽中伤，生疮，不能语言，声不出者，苦酒汤主之。'")
SYN["Shengbuchu"] = dict(
    alt=["声不出", "失音"],
    hid=["说不出话", "嗓子哑了", "发不出声"],
    definition="声音不能发出。少阴咽伤或肺气不利。",
    note="伤寒论第312条。")
SYN["Shenghe"] = dict(
    alt=["声喝", "声嘶"],
    hid=["声音嘶哑", "嗓子哑"],
    definition="声音嘶哑。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Koutuxian"] = dict(
    alt=["口吐涎"],
    hid=["嘴里流口水", "流涎"],
    definition="口中流涎。",
    note="")
SYN["Shejinanyan"] = dict(
    alt=["舌即难言"],
    hid=["舌头不听使唤说不出话"],
    definition="舌强难以言语。中风之候。",
    note="金匮要略·中风历节病：'邪入于脏，舌即难言，口吐涎。'")
SYN["Tunongrumizhou"] = dict(
    alt=["吐脓如米粥"],
    hid=["吐的脓像米粥"],
    definition="吐脓如米粥状。肺痈溃脓之候。",
    note="金匮要略·肺痿肺痈咳嗽上气。")
SYN["Yuyannanchu"] = dict(
    alt=["语言难出"],
    hid=["说话困难", "说不出话"],
    definition="言语难以发出。",
    note="伤寒论第6条。")
SYN["Xiaogushanji"] = dict(
    alt=["消谷善饥"],
    hid=["吃得多还饿", "容易饿", "特别能吃"],
    definition="食欲亢进，食而易饥。胃火亢盛。",
    note="伤寒论第257条：'病人无表里证，发热七八日，虽脉浮数者，可下之……消谷善饥。'")

# ========== 五、咳喘类 ==========
SYN["Kesou"] = dict(
    alt=["咳嗽", "咳"],
    hid=["咳嗽", "咳", "老咳嗽", "嗓子痒咳"],
    definition="肺气上逆而咳。",
    note="金匮要略·肺痿肺痈咳嗽上气。")
SYN["Ketuo"] = dict(
    alt=["咳唾"],
    hid=["咳嗽吐痰", "咳痰"],
    definition="咳嗽吐痰。",
    note="金匮要略·痰饮。")
SYN["Keershangqi"] = dict(
    alt=["咳而上气"],
    hid=["咳得喘不上气", "咳嗽气往上冲"],
    definition="咳嗽兼气逆上冲。肺胀之候。",
    note="金匮要略·肺痿肺痈咳嗽上气：'咳而上气，喉中水鸡声，射干麻黄汤主之。'")
SYN["Keni"] = dict(
    alt=["咳逆", "咳逆上气"],
    hid=["咳得气逆", "咳嗽打嗝"],
    definition="咳嗽气逆。",
    note="金匮要略·痰饮。")
SYN["Chuan"] = dict(
    alt=["气喘", "喘息"],
    hid=["喘", "气喘", "呼吸急促"],
    definition="呼吸急促，气息迫促。",
    note="伤寒论第35条：'无汗而喘'，麻黄汤证。")
SYN["Duanqi"] = dict(
    alt=["短气"],
    hid=["气短", "喘不上气", "气不够用"],
    definition="呼吸短促，气不接续。",
    note="金匮要略·胸痹心痛短气病。")
SYN["Shaoqi"] = dict(
    alt=["少气", "气少"],
    hid=["乏力", "没劲", "浑身没劲", "气力不足", "容易累"],
    definition="气力不足，言语无力。虚劳或气虚之候。",
    note="金匮要略·血痹虚劳：'虚劳里急，悸，衄，腹中痛，梦失精，四肢酸疼，手足烦热，咽干口燥，小建中汤主之。'")
SYN["Shangqi"] = dict(
    alt=["上气"],
    hid=["气往上冲", "气逆"],
    definition="气逆上冲。",
    note="金匮要略·肺痿肺痈咳嗽上气。")
SYN["Budexi"] = dict(
    alt=["不得息"],
    hid=["喘不过气", "气透不过来"],
    definition="呼吸不得平顺。",
    note="金匮要略·痰饮。")
SYN["Shishituzhuo"] = dict(
    alt=["时时吐浊"],
    hid=["老是吐浊痰"],
    definition="时时吐出浊痰。",
    note="金匮要略·肺痿肺痈咳嗽上气。")
SYN["Houzhongshuijisheng"] = dict(
    alt=["喉中水鸡声"],
    hid=["喉咙里有水鸡叫声", "喉中痰鸣如水鸡"],
    definition="喉中痰鸣如水鸡之声。寒饮射肺之候。",
    note="金匮要略·肺痿肺痈咳嗽上气：'咳而上气，喉中水鸡声，射干麻黄汤主之。'")
SYN["Huonishangqi"] = dict(
    alt=["火逆上气"],
    hid=["虚火上冲气逆"],
    definition="虚火挟气上逆。",
    note="金匮要略·肺痿肺痈咳嗽上气：'火逆上气，咽喉不利，止逆下气者，麦门冬汤主之。'")

# ========== 六、心胸类 ==========
SYN["Xinji"] = dict(
    alt=["心悸", "心动悸"],
    hid=["心慌", "心跳快", "心跳得厉害", "心里发慌"],
    definition="心中悸动不安。水饮凌心或气血不足。",
    note="伤寒论第177条：'伤寒脉结代，心动悸，炙甘草汤主之。'")
SYN["Xinxiajidong"] = dict(
    alt=["心下悸动"],
    hid=["心口窝跳", "胃脘部跳动"],
    definition="心下（胃脘）部位悸动。水饮内停。",
    note="伤寒论第127条：'心下悸'。")
SYN["Qixiaji"] = dict(
    alt=["脐下悸"],
    hid=["肚脐下跳", "小腹跳动"],
    definition="脐下悸动。欲作奔豚之候。",
    note="伤寒论第65条：'发汗后，其人脐下悸者，欲作奔豚，茯苓桂枝甘草大枣汤主之。'")
SYN["Xinxiaji"] = dict(
    alt=["心下急"],
    hid=["心口窝发紧", "胃脘拘急"],
    definition="心下拘急不舒。少阳兼阳明之候。",
    note="伤寒论第103条：'呕不止，心下急，郁郁微烦者……大柴胡汤主之。'")
SYN["Xinxiapi"] = dict(
    alt=["心下痞", "痞"],
    hid=["胃胀", "胃里堵得慌", "心口窝堵", "胃部胀满"],
    definition="心下（胃脘）痞塞不通，按之濡软。中焦气机不利。",
    note="伤寒论第149条：'但满而不痛者，此为痞，柴胡不中与之，宜半夏泻心汤。'胡老：痞为按之濡、不痛。")
SYN["Xinxiapiying"] = dict(
    alt=["心下痞硬"],
    hid=["胃脘胀硬", "心口窝又胀又硬"],
    definition="心下痞塞而硬。",
    note="伤寒论第158条：'伤寒中风，医反下之……心下痞硬而满。'")
SYN["Xinxiajian"] = dict(
    alt=["心下坚"],
    hid=["胃脘坚硬", "心口窝发硬"],
    definition="心下坚硬。",
    note="金匮要略·水气病：'心下坚，大如盘，边如旋盘。'")
SYN["Xinxiapijian"] = dict(
    alt=["心下痞坚"],
    hid=["胃脘痞硬坚满"],
    definition="心下痞满而坚硬。",
    note="金匮要略·痰饮：'膈间支饮，其人喘满，心下痞坚，面色黧黑。'")
SYN["Xinxiakuan"] = dict(
    alt=["心下宽"],
    hid=["胃脘宽松"],
    definition="心下宽松不胀。",
    note="")
SYN["Xinxianiman"] = dict(
    alt=["心下逆满"],
    hid=["胃脘胀满气逆"],
    definition="心下胀满而气逆。",
    note="伤寒论第67条：'心下逆满，气上冲胸，起则头眩。'")
SYN["Xinxiaman"] = dict(
    alt=["心下满"],
    hid=["胃脘胀满", "心口窝胀"],
    definition="心下胀满。",
    note="伤寒论第28条：'服桂枝汤，或下之，仍头项强痛，翕翕发热，无汗，心下满微痛，小便不利者，桂枝去桂加茯苓白术汤主之。'")
SYN["Xinxiatong"] = dict(
    alt=["心下痛", "胃脘痛"],
    hid=["胃疼", "胃痛", "心口窝疼", "胃脘疼"],
    definition="心下（胃脘）疼痛。",
    note="伤寒论第135条：'伤寒六七日，结胸热实，脉沉而紧，心下痛，按之石硬者，大陷胸汤主之。'")
SYN["Xinxiazhijie"] = dict(
    alt=["心下支结"],
    hid=["心口窝支撑结滞"],
    definition="心下支撑结滞不舒。少阳之候。",
    note="伤寒论第146条：'伤寒六七日……心下支结，外证未去者，柴胡桂枝汤主之。'")
SYN["Xinzhongpi"] = dict(
    alt=["心中痞"],
    hid=["心中痞塞", "心里堵"],
    definition="心中痞塞不舒。",
    note="金匮要略·胸痹心痛短气病。")
SYN["Xinzhongtengre"] = dict(
    alt=["心中疼热"],
    hid=["心里又疼又热"],
    definition="心中疼痛而热。蛔厥之候。",
    note="伤寒论第338条：'蛔厥者……心中疼热。'")
SYN["Xinzhongaonao"] = dict(
    alt=["心中懊憹", "懊憹"],
    hid=["心里烦闷难受", "心里说不出的难受", "心烦意乱"],
    definition="心中烦闷懊憹，难以名状。热扰胸膈之候。",
    note="伤寒论第76条：'发汗吐下后，虚烦不得眠，若剧者，必反复颠倒，心中懊憹，栀子豉汤主之。'")
SYN["Xinzhongehanbuzu"] = dict(
    alt=["心中恶寒不足"],
    hid=["心里发冷不足"],
    definition="心中恶寒而不足。",
    note="金匮要略·中风历节病。")
SYN["Xiongzhongzhi"] = dict(
    alt=["胸中窒"],
    hid=["胸口堵", "胸中堵塞感", "胸口发闷堵得慌"],
    definition="胸中窒塞不舒。热扰胸膈之候。",
    note="伤寒论第77条：'发烦热，胸中窒者，栀子豉汤主之。'")
SYN["Xinzhongji"] = dict(
    alt=["心中饥"],
    hid=["心里觉得饿"],
    definition="心中嘈杂如饥。",
    note="金匮要略·妇人杂病。")
SYN["Xinfan"] = dict(
    alt=["心烦", "烦"],
    hid=["心烦", "心里烦躁", "烦得慌"],
    definition="心中烦扰不安。热扰心神之候。",
    note="伤寒论第76条。")
SYN["Weifan"] = dict(
    alt=["微烦"],
    hid=["有点烦", "稍微烦躁"],
    definition="轻微心烦。",
    note="伤寒论第103条：'郁郁微烦'。")
SYN["Yuyuweifan"] = dict(
    alt=["郁郁微烦"],
    hid=["闷闷地有点烦"],
    definition="郁郁不舒而微烦。",
    note="伤寒论第103条。")
SYN["Fanzao"] = dict(
    alt=["烦躁", "烦燥"],
    hid=["烦躁", "心里烦", "坐立不安", "又烦又躁"],
    definition="心烦而躁动不安。热盛或阳虚阴盛皆可见。",
    note="伤寒论第38条：'太阳中风，脉浮紧，发热恶寒，身疼痛，不汗出而烦躁者，大青龙汤主之。'")
SYN["Fanzaoyusi"] = dict(
    alt=["烦躁欲死"],
    hid=["烦躁得要死", "烦得受不了"],
    definition="烦躁之极。",
    note="伤寒论第309条：'少阴病，吐利，手足逆冷，烦躁欲死者，吴茱萸汤主之。'")
SYN["Xiongman"] = dict(
    alt=["胸满"],
    hid=["胸闷", "胸口闷", "胸中满闷"],
    definition="胸部胀满。",
    note="伤寒论第36条：'太阳与阳明合病，喘而胸满者，不可下，宜麻黄汤。'")
SYN["Xiongzhongqisai"] = dict(
    alt=["胸中气塞"],
    hid=["胸中气堵", "胸口气塞"],
    definition="胸中气机闭塞。",
    note="金匮要略·胸痹心痛短气病：'胸中气塞，短气，茯苓杏仁甘草汤主之。'")
SYN["Xiongzhongpiying"] = dict(
    alt=["胸中痞硬"],
    hid=["胸口痞硬"],
    definition="胸中痞塞而硬。",
    note="伤寒论第166条：'病如桂枝证，头不痛，项不强，寸脉微浮，胸中痞硬，气上冲喉咽不得息者，此为胸有寒也，当吐之，宜瓜蒂散。'")
SYN["Xiongzhongyoure"] = dict(
    alt=["胸中有热"],
    hid=["胸中发热", "胸口热"],
    definition="胸中有热。",
    note="伤寒论第173条：'伤寒，胸中有热，胃中有邪气，腹中痛，欲呕吐者，黄连汤主之。'")
SYN["Xiongzhongfan"] = dict(
    alt=["胸中烦"],
    hid=["胸中烦热", "胸口烦"],
    definition="胸中烦扰。",
    note="伤寒论第96条：'胸中烦而不呕者，去半夏、人参，加栝蒌实一枚。'")
SYN["Xiongzhongjiacuo"] = dict(
    alt=["胸中甲错"],
    hid=["胸中肌肤粗糙如鳞甲"],
    definition="胸中肌肤粗糙如鳞甲。瘀血之候。",
    note="金匮要略·血痹虚劳：'内有干血，肌肤甲错。'")
SYN["Xiongtong"] = dict(
    alt=["胸痛"],
    hid=["胸痛", "胸口疼"],
    definition="胸部疼痛。",
    note="金匮要略·胸痹心痛短气病。")
SYN["Xiongbi"] = dict(
    alt=["胸痹"],
    hid=["胸痹", "胸口闷痛憋气"],
    definition="胸中闭塞而痛，甚则痛彻背。阳微阴弦之候。",
    note="金匮要略·胸痹心痛短气病：'胸痹之病，喘息咳唾，胸背痛，短气……栝蒌薤白白酒汤主之。'")
SYN["Xiongbihuanji"] = dict(
    alt=["胸痹缓急"],
    hid=["胸痹时缓时急"],
    definition="胸痹时缓时急。",
    note="金匮要略·胸痹心痛短气病：'胸痹缓急者，薏苡附子散主之。'")
SYN["Xintong"] = dict(
    alt=["心痛"],
    hid=["心口疼", "心前区痛"],
    definition="心胸部疼痛。",
    note="金匮要略·胸痹心痛短气病。")
SYN["Xintongchebei"] = dict(
    alt=["心痛彻背"],
    hid=["心口疼连到后背", "心痛牵连后背"],
    definition="心痛牵引及背。",
    note="金匮要略·胸痹心痛短气病：'心痛彻背，背痛彻心，乌头赤石脂丸主之。'")
SYN["Beitongchexin"] = dict(
    alt=["背痛彻心"],
    hid=["后背疼连到心口"],
    definition="背痛牵引及心。",
    note="金匮要略·胸痹心痛短气病。")
SYN["Xinxuantong"] = dict(
    alt=["心悬痛"],
    hid=["心口悬空样疼"],
    definition="心中悬空而痛。",
    note="金匮要略·胸痹心痛短气病：'心中痞，诸逆心悬痛，桂枝生姜枳实汤主之。'")
SYN["Xiongxiekuman"] = dict(
    alt=["胸胁苦满", "胸胁满", "胁满"],
    hid=["两边肋骨下面胀痛", "两边肋骨胀痛", "肋骨下胀痛", "胁肋胀痛", "两侧肋部胀满", "肋骨下胀", "胁下胀痛", "两肋胀痛", "胸胁胀满"],
    definition="胸胁部胀满不舒，甚则疼痛。少阳病特异性指征，邪结少阳、枢机不利。",
    note="伤寒论第96条：'伤寒五六日中风，往来寒热，胸胁苦满，嘿嘿不欲饮食，心烦喜呕……小柴胡汤主之。'胡老：胸胁苦满为少阳病第一主症，按之亦满痛。")
SYN["Xiongxiezhiman"] = dict(
    alt=["胸胁支满"],
    hid=["胸胁支撑胀满"],
    definition="胸胁支撑胀满。痰饮之候。",
    note="金匮要略·痰饮：'心下有痰饮，胸胁支满，目眩，苓桂术甘汤主之。'")
SYN["Xietong"] = dict(
    alt=["胁痛"],
    hid=["胁痛", "肋骨下疼", "两侧肋痛"],
    definition="胁部疼痛。",
    note="金匮要略·五脏风寒积聚病。")
SYN["Xiexiapiying"] = dict(
    alt=["胁下痞硬"],
    hid=["胁下痞硬", "肋骨下硬块"],
    definition="胁下痞塞而硬。少阳之候。",
    note="伤寒论第96条：'胁下痞硬者，去大枣，加牡蛎四两。'")
SYN["Xiexiapiantong"] = dict(
    alt=["胁下偏痛"],
    hid=["一侧胁下痛", "胁下偏侧疼痛"],
    definition="胁下一侧疼痛。寒实内结之候。",
    note="金匮要略·腹满寒疝宿食：'胁下偏痛，发热，其脉紧弦，此寒也，以温药下之，宜大黄附子汤。'")
SYN["Xiexiazhengjia"] = dict(
    alt=["胁下癥瘕"],
    hid=["胁下有包块", "胁下痞块"],
    definition="胁下有癥瘕积块。",
    note="金匮要略·疟病：'病疟以月一日发，当以十五日愈……此结为癥瘕，名曰疟母。'")
SYN["Xinxiongdahantong"] = dict(
    alt=["心胸大寒痛"],
    hid=["心胸大寒而痛"],
    definition="心胸大寒疼痛。",
    note="金匮要略·腹满寒疝宿食：'心胸中大寒痛，呕不能饮食……大建中汤主之。'")
SYN["Xiongzhongtong"] = dict(
    alt=["胸中痛"],
    hid=["胸中疼"],
    definition="胸中疼痛。",
    note="金匮要略·胸痹心痛短气病。")
SYN["Beihanlengruzhangda"] = dict(
    alt=["背寒冷如掌大"],
    hid=["后背一块像手掌大那么冷"],
    definition="背部寒冷如手掌大小一块。留饮之候。",
    note="金匮要略·痰饮：'夫心下有留饮，其人背寒冷如手大。'")
SYN["Xiexiatongyinquepen"] = dict(
    alt=["胁下痛引缺盆"],
    hid=["胁下痛牵连锁骨窝"],
    definition="胁下疼痛牵引缺盆。",
    note="金匮要略·痰饮。")
SYN["Xiongxiekutong"] = dict(
    alt=["胸胁苦痛"],
    hid=["胸胁疼痛"],
    definition="胸胁疼痛。",
    note="")
SYN["Xiexianiqiangxin"] = dict(
    alt=["胁下逆抢心"],
    hid=["胁下气逆冲心"],
    definition="胁下气逆上冲于心。",
    note="金匮要略·胸痹心痛短气病：'胸痹心中痞，留气结在胸，胸满，胁下逆抢心，枳实薤白桂枝汤主之。'")
SYN["Xiexiaman"] = dict(
    alt=["胁下满"],
    hid=["胁下胀满"],
    definition="胁下胀满。",
    note="伤寒论第96条。")

# ========== 七、脘腹类 ==========
SYN["Fuman"] = dict(
    alt=["腹满", "腹胀满", "腹胀"],
    hid=["肚子胀", "腹胀", "肚子胀满", "肚子发胀", "腹部胀满"],
    definition="腹部胀满。太阴病提纲证之一，脾虚湿盛或阳明腑实。",
    note="伤寒论第273条：'太阴之为病，腹满而吐，食不下，自利益甚，时腹自痛。'胡老：腹满须辨虚实，虚则太阴，实则阳明。")
SYN["Futong"] = dict(
    alt=["腹痛", "腹中痛"],
    hid=["肚子疼", "肚子痛", "腹痛"],
    definition="腹部疼痛。",
    note="伤寒论第100条：'伤寒，阳脉涩，阴脉弦，法当腹中急痛，先与小建中汤。'")
SYN["Fuzhonghan"] = dict(
    alt=["腹中寒"],
    hid=["肚子里发冷", "腹部寒凉"],
    definition="腹中寒冷。里寒之候。",
    note="金匮要略·腹满寒疝宿食。")
SYN["Fuzhongjiaotong"] = dict(
    alt=["腹中㽲痛", "㽲痛"],
    hid=["肚子绞痛", "腹中拘急绞痛"],
    definition="腹中拘急绞痛。",
    note="金匮要略·妇人杂病。")
SYN["Fuzhongleiming"] = dict(
    alt=["腹中雷鸣"],
    hid=["肚子里咕噜响", "肚子雷鸣", "腹中肠鸣如雷"],
    definition="腹中肠鸣如雷。水气内停、中焦虚寒。",
    note="伤寒论第157条：'心下痞硬而满，干呕心烦不得安……腹中雷鸣下利者，甘草泻心汤主之。'")
SYN["Changming"] = dict(
    alt=["肠鸣"],
    hid=["肚子响", "肚子咕咕叫", "肠鸣音"],
    definition="肠中鸣响。",
    note="金匮要略·痰饮：'水走肠间，沥沥有声，谓之痰饮。'")
SYN["Changmingruzoushui"] = dict(
    alt=["肠鸣如走水"],
    hid=["肚子响像流水"],
    definition="肠鸣如水流之声。",
    note="金匮要略·痰饮。")
SYN["Fupiji"] = dict(
    alt=["腹皮急"],
    hid=["腹皮绷紧", "肚子皮肤发紧"],
    definition="腹壁拘急。",
    note="金匮要略·疮痈肠痈浸淫病：'肠痈之为病，其身甲错，腹皮急，按之濡如肿状。'")
SYN["Shaofutong"] = dict(
    alt=["少腹痛"],
    hid=["小肚子疼", "下腹痛", "小腹痛"],
    definition="少腹（下腹）疼痛。",
    note="伤寒论第106条：'太阳病不解，热结膀胱，其人如狂，血自下，下者愈。'")
SYN["Shaofuxianji"] = dict(
    alt=["少腹弦急"],
    hid=["小腹拘紧发硬"],
    definition="少腹拘急紧张。",
    note="金匮要略·血痹虚劳：'夫失精家，少腹弦急，阴头寒。'")
SYN["Shaofuman"] = dict(
    alt=["少腹满"],
    hid=["小肚子胀", "小腹胀满"],
    definition="少腹胀满。",
    note="伤寒论第126条：'伤寒有热，少腹满，应小便不利，今反利者，为有血也。'")
SYN["Shaofujuji"] = dict(
    alt=["少腹拘急"],
    hid=["小腹拘急不舒"],
    definition="少腹拘急。",
    note="金匮要略·血痹虚劳：'虚劳腰痛，少腹拘急，小便不利者，八味肾气丸主之。'")
SYN["Shaofuliji"] = dict(
    alt=["少腹里急"],
    hid=["小腹拘急疼痛"],
    definition="少腹里急。",
    note="金匮要略·妇人杂病。")
SYN["Liji"] = dict(
    alt=["里急"],
    hid=["腹中拘急", "肚子里抽紧"],
    definition="腹中拘急不舒。",
    note="金匮要略·血痹虚劳：'虚劳里急，悸，衄，腹中痛……小建中汤主之。'")
SYN["Shifuzitong"] = dict(
    alt=["时腹自痛"],
    hid=["肚子时不时自己疼"],
    definition="腹部时时自痛。太阴病提纲证之一。",
    note="伤寒论第273条：'太阴之为病，腹满而吐，食不下，自利益甚，时腹自痛。'")
SYN["Zhengkuai"] = dict(
    alt=["癥块", "癥瘕"],
    hid=["包块", "肚子有硬块", "痞块"],
    definition="腹中结块。",
    note="金匮要略·疟病：'此结为癥瘕。'")
SYN["Wujiju"] = dict(
    alt=["无积聚"],
    hid=["没有包块"],
    definition="腹中无积聚。",
    note="")
SYN["Xinxiaanzhimantong"] = dict(
    alt=["心下按之满痛"],
    hid=["按心口窝又胀又痛"],
    definition="心下按之满痛。",
    note="金匮要略·腹满寒疝宿食：'按之心下满痛者，此为实也，当下之，宜大柴胡汤。'")
SYN["Juan"] = dict(
    alt=["拒按"],
    hid=["按着疼不让按", "一按就疼"],
    definition="腹部拒按。实邪内结之征。",
    note="胡老：拒按为实，喜按为虚。")
SYN["Anzhijitongrulin"] = dict(
    alt=["按之即痛如淋"],
    hid=["一按就疼像淋证"],
    definition="按之即痛如淋。",
    note="金匮要略·疮痈肠痈浸淫病。")
SYN["Anzhiruruzhongzhuang"] = dict(
    alt=["按之濡如肿状"],
    hid=["按之柔软如肿"],
    definition="按之濡软如肿状。",
    note="金匮要略·疮痈肠痈浸淫病。")
SYN["Fuzhongrudaiwuqianqian"] = dict(
    alt=["腹重如带五千钱"],
    hid=["腰腹沉重像坠着钱"],
    definition="腰腹沉重如带五千钱。寒湿着肾之候。",
    note="金匮要略·五脏风寒积聚病：'肾着之病，其人身体重，腰中冷，如坐水中……腹重如带五千钱，甘姜苓术汤主之。'")
SYN["Shaofuzhengkuai"] = dict(
    alt=["少腹癥块"],
    hid=["小腹有硬块"],
    definition="少腹癥块。",
    note="")
SYN["Shaofuzhongpi"] = dict(
    alt=["少腹肿痞"],
    hid=["小腹肿硬"],
    definition="少腹肿痞。",
    note="金匮要略·疮痈肠痈浸淫病。")
SYN["Shaofujijie"] = dict(
    alt=["少腹急结"],
    hid=["小腹拘急结硬"],
    definition="少腹急结。瘀血之候。",
    note="伤寒论第106条：'太阳病不解，热结膀胱……少腹急结者，乃可攻之，宜桃核承气汤。'")
SYN["Raoqitong"] = dict(
    alt=["绕脐痛"],
    hid=["肚脐周围疼", "绕肚脐疼"],
    definition="绕脐疼痛。",
    note="金匮要略·腹满寒疝宿食：'寒疝绕脐痛，若发则白汗出，手足厥冷。'")
SYN["Fuzhongjitong"] = dict(
    alt=["腹中急痛"],
    hid=["肚子急剧疼痛"],
    definition="腹中急剧疼痛。",
    note="伤寒论第100条：'法当腹中急痛，先与小建中汤。'")
SYN["Shaofujiantong"] = dict(
    alt=["少腹坚痛"],
    hid=["小腹坚硬疼痛"],
    definition="少腹坚硬疼痛。",
    note="金匮要略·妇人产后病。")
SYN["Elubujin"] = dict(
    alt=["恶露不尽"],
    hid=["恶露不净", "产后恶露不止"],
    definition="产后恶露不尽。",
    note="金匮要略·妇人产后病。")
SYN["Shaofuyingman"] = dict(
    alt=["少腹硬满"],
    hid=["小腹硬满"],
    definition="少腹硬满。瘀血之候。",
    note="伤寒论第124条：'太阳病六七日，表证仍在，脉微而沉，反不结胸，其人发狂者，以热在下焦，少腹当硬满。'")
SYN["Shaofuehan"] = dict(
    alt=["少腹恶寒"],
    hid=["小腹怕冷"],
    definition="少腹恶寒。",
    note="")
SYN["Qichongjitong"] = dict(
    alt=["气冲急痛"],
    hid=["气冲部位急痛"],
    definition="气冲穴处急痛。",
    note="金匮要略·妇人杂病。")
SYN["Raoqihanshan"] = dict(
    alt=["绕脐寒疝"],
    hid=["绕脐寒疝痛"],
    definition="绕脐寒疝疼痛。",
    note="金匮要略·腹满寒疝宿食。")
SYN["Furugu"] = dict(
    alt=["腹如鼓"],
    hid=["肚子胀得像鼓", "腹胀如鼓"],
    definition="腹部胀大如鼓。",
    note="金匮要略·水气病。")
SYN["Bangguangji"] = dict(
    alt=["膀胱急"],
    hid=["膀胱拘急"],
    definition="膀胱拘急不舒。",
    note="金匮要略·黄疸病。")
SYN["Shitong"] = dict(
    alt=["时痛", "时时痛"],
    hid=["一阵一阵疼", "时不时疼", "有时疼", "疼一阵好一阵"],
    definition="腹部阵发性疼痛，时作时止。太阴病之候，桂枝加芍药汤证之特异性指征。",
    note="伤寒论第279条：'本太阳病，医反下之，因尔腹满时痛者，属太阴也，桂枝加芍药汤主之；大实痛者，桂枝加大黄汤主之。'胡老：腹满时痛为太阴，属桂枝加芍药汤。")

# ========== 八、二便类 ==========
SYN["Dabiannan"] = dict(
    alt=["大便难", "大便困难"],
    hid=["便秘", "拉不出来", "大便难解", "排便困难"],
    definition="大便排出困难。",
    note="伤寒论第252条：'大便难，身微热者，此为实也。'")
SYN["Dabianying"] = dict(
    alt=["大便硬", "大便燥硬"],
    hid=["大便干", "大便硬", "大便干燥", "屎硬"],
    definition="大便坚硬。阳明腑实之候。",
    note="伤寒论第208条：'手足濈然汗出者，此大便已硬也。'")
SYN["Dabiantang"] = dict(
    alt=["大便溏"],
    hid=["大便稀", "大便不成形", "拉稀", "大便软"],
    definition="大便稀溏。脾虚湿盛之候。",
    note="伤寒论第229条：'阳明病，发潮热，大便溏，小便自可，胸胁满不去者，与小柴胡汤。'")
SYN["Dabianchuyinghoutang"] = dict(
    alt=["大便初硬后溏"],
    hid=["大便先干后稀"],
    definition="大便初头硬后则溏。",
    note="伤寒论第191条：'阳明病，若中寒者，不能食，小便不利，手足濈然汗出，此欲作固瘕，必大便初硬后溏。'")
SYN["Bianxue"] = dict(
    alt=["便血"],
    hid=["大便带血", "便血", "拉血"],
    definition="大便下血。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病：'下血，先便后血，此远血也，黄土汤主之。'")
SYN["Xianbianhoubianxue"] = dict(
    alt=["先便后血", "远血"],
    hid=["先拉屎后出血"],
    definition="先大便后下血，为远血。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病：'下血，先便后血，此远血也，黄土汤主之。'")
SYN["Xianxuehoubian"] = dict(
    alt=["先血后便", "近血"],
    hid=["先出血后拉屎"],
    definition="先下血后大便，为近血。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病：'下血，先血后便，此近血也，赤小豆当归散主之。'")
SYN["Nongxue"] = dict(
    alt=["脓血"],
    hid=["脓血便", "大便有脓血"],
    definition="大便夹脓血。",
    note="金匮要略·呕吐哕下利病。")
SYN["Xiaobianbuli"] = dict(
    alt=["小便不利", "小便难"],
    hid=["尿少", "排尿不畅", "尿不出来", "小便不畅", "尿量少"],
    definition="小便排出不畅或量少。",
    note="伤寒论第71条：'若脉浮，小便不利，微热消渴者，五苓散主之。'")
SYN["Xiaobianshu"] = dict(
    alt=["小便数"],
    hid=["尿频", "老想小便", "小便次数多"],
    definition="小便次数多。",
    note="金匮要略·肺痿肺痈咳嗽上气：'肺痿吐涎沫而不咳者，其人不渴，必遗尿，小便数。'")
SYN["Xiaobianzili"] = dict(
    alt=["小便自利"],
    hid=["小便正常", "小便自通"],
    definition="小便自利。",
    note="伤寒论第124条：'少腹当硬满，小便自利者，下血乃愈。'")
SYN["Xiaobianchi"] = dict(
    alt=["小便赤"],
    hid=["尿发红", "小便发红"],
    definition="小便色赤。里热之候。",
    note="")
SYN["Xiaobianhuang"] = dict(
    alt=["小便黄"],
    hid=["尿黄", "小便发黄"],
    definition="小便色黄。湿热之候。",
    note="")
SYN["Xiaobiansebai"] = dict(
    alt=["小便色白"],
    hid=["尿清", "小便清"],
    definition="小便色白清长。下焦虚寒之候。",
    note="伤寒论第282条：'少阴病，欲吐不吐，心烦但欲寐，五六日自利而渴者，属少阴也，虚故引水自救。若小便色白者，少阴病形悉具。'")
SYN["Yiniao"] = dict(
    alt=["遗尿", "尿床"],
    hid=["尿床", "憋不住尿", "遗尿"],
    definition="小便不自主排出。",
    note="金匮要略·肺痿肺痈咳嗽上气。")
SYN["Xiali"] = dict(
    alt=["下利", "腹泻", "泄泻", "自利"],
    hid=["拉肚子", "腹泻", "拉稀", "闹肚子", "拉稀水", "大便稀"],
    definition="大便稀薄或次数增多。太阴、少阴、厥阴皆有下利，须辨寒热虚实。",
    note="伤寒论第273条：'太阴之为病……自利益甚。'胡老：下利须辨热利、寒利、虚利。")
SYN["Xialiqi"] = dict(
    alt=["下利气"],
    hid=["拉肚子带屁", "下利兼矢气"],
    definition="下利兼矢气。",
    note="金匮要略·呕吐哕下利病：'下利气者，当利其小便。'")
SYN["Xialiqinggu"] = dict(
    alt=["下利清谷"],
    hid=["拉未消化的食物", "拉清水完谷", "拉不消化的东西"],
    definition="下利完谷不化，清稀如水。少阴、太阴虚寒之候。",
    note="伤寒论第317条：'少阴病，下利清谷，里寒外热，手足厥逆……通脉四逆汤主之。'")
SYN["Xiazhong"] = dict(
    alt=["下重", "里急后重"],
    hid=["肛门坠胀", "想拉又拉不出", "拉完还想拉"],
    definition="肛门重坠，里急后重。",
    note="伤寒论第365条：'下利，脉沉弦者，下重也。'")
SYN["Lijihouchong"] = dict(
    alt=["里急后重"],
    hid=["想拉又拉不出", "拉不干净", "肛门坠胀"],
    definition="腹痛急迫而便意频，排便不爽。",
    note="伤寒论第365条。")
SYN["Shiqi"] = dict(
    alt=["失气", "矢气"],
    hid=["放屁", "排气"],
    definition="肛门排气。",
    note="伤寒论第209条：'欲知之法，少与小承气汤，汤入腹中，转失气者，此有燥屎也。'")
SYN["Gubuhua"] = dict(
    alt=["谷不化", "完谷不化"],
    hid=["拉不消化的食物", "食物没消化就拉出来"],
    definition="饮食不化而排出。脾胃虚寒之候。",
    note="伤寒论第273条。")
SYN["Xiaobianyiyinteng"] = dict(
    alt=["小便已阴疼"],
    hid=["尿完尿道疼"],
    definition="小便后阴部疼痛。",
    note="伤寒论第88条。")
SYN["Xialirishushixing"] = dict(
    alt=["下利日数十行"],
    hid=["一天拉几十次"],
    definition="下利一日数十次。",
    note="伤寒论第158条：'医反下之，其人下利日数十行，谷不化，腹中雷鸣。'")
SYN["Dabianzhananzhayi"] = dict(
    alt=["大便乍难乍易"],
    hid=["大便时难时易"],
    definition="大便忽难忽易。",
    note="伤寒论第242条：'大便乍难乍易，时有微热，喘冒不能卧者，有燥屎也。'")
SYN["Xiaobianfanduo"] = dict(
    alt=["小便反多"],
    hid=["尿反而多"],
    definition="小便反多。消渴之候。",
    note="金匮要略·消渴小便不利淋病。")
SYN["Xiabaiwu"] = dict(
    alt=["下白物"],
    hid=["白带多", "下白色分泌物"],
    definition="阴道下白色分泌物。",
    note="金匮要略·妇人杂病：'妇人经水闭不利，脏坚癖不止，中有干血，下白物，矾石丸主之。'")
SYN["Niaoxue"] = dict(
    alt=["尿血", "溺血"],
    hid=["尿血", "小便带血", "血尿"],
    definition="小便出血。",
    note="金匮要略·五脏风寒积聚病。")
SYN["Qingbianyuzike"] = dict(
    alt=["清便欲自可"],
    hid=["大便尚可"],
    definition="大便尚能自调。",
    note="伤寒论第23条：'清便欲自可。'")
SYN["Budabian"] = dict(
    alt=["不大便"],
    hid=["不拉屎", "几天没大便", "没排便"],
    definition="不大便。阳明腑实之候。",
    note="伤寒论第212条：'不大便五六日，上至十余日……大承气汤主之。'")
SYN["Bugengyi"] = dict(
    alt=["不更衣"],
    hid=["不排便", "没大便"],
    definition="不更衣，即不大便。",
    note="伤寒论第181条：'不更衣，内实，大便难者，此名阳明也。'")
SYN["Xialibuzhi"] = dict(
    alt=["下利不止"],
    hid=["拉肚子止不住", "一直拉"],
    definition="下利不止。",
    note="伤寒论第159条：'伤寒服汤药，下利不止，心下痞硬。'")
SYN["Xialinongxue"] = dict(
    alt=["下利脓血"],
    hid=["拉脓血", "大便带脓血"],
    definition="下利夹脓血。热利之候。",
    note="伤寒论第371条：'热利下重者，白头翁汤主之。'")
SYN["Xiaobianfanshao"] = dict(
    alt=["小便反少"],
    hid=["尿反而少"],
    definition="小便反少。",
    note="金匮要略·痉湿暍病。")
SYN["Zilierke"] = dict(
    alt=["自利而渴"],
    hid=["拉肚子还口渴"],
    definition="自下利而口渴。少阴之候。",
    note="伤寒论第282条：'五六日自利而渴者，属少阴也。'")
SYN["Budeqianhou"] = dict(
    alt=["不得前后"],
    hid=["大小便都不通"],
    definition="大小便皆不通。",
    note="金匮要略·腹满寒疝宿食。")
SYN["Jiuli"] = dict(
    alt=["久利"],
    hid=["长期拉肚子", "慢性腹泻"],
    definition="久利不愈。",
    note="伤寒论第338条：'乌梅丸……又主久利。'")
SYN["Xiaobiannan"] = dict(
    alt=["小便难"],
    hid=["排尿困难", "尿不出来"],
    definition="小便困难。",
    note="伤寒论第20条：'小便难，四肢微急。'")
SYN["Xiaobianzidiao"] = dict(
    alt=["小便自调"],
    hid=["小便正常"],
    definition="小便自调。",
    note="")
SYN["Xiaobianhuangchi"] = dict(
    alt=["小便黄赤"],
    hid=["尿黄赤", "小便又黄又红"],
    definition="小便黄赤。湿热之候。",
    note="")
SYN["Xiaobianqing"] = dict(
    alt=["小便清"],
    hid=["尿清", "小便清长"],
    definition="小便清长。下焦虚寒之候。",
    note="伤寒论第56条：'小便清者，知不在里，仍在表也。'")
SYN["Dabianmijie"] = dict(
    alt=["大便秘结"],
    hid=["便秘", "大便干结", "拉不出来"],
    definition="大便秘结不通。",
    note="")

# ========== 九、呕吐哕类 ==========
SYN["Outu"] = dict(
    alt=["呕吐"],
    hid=["呕吐", "吐", "恶心呕吐"],
    definition="胃气上逆，呕吐食物或痰涎。",
    note="金匮要略·呕吐哕下利病。")
SYN["Chaoshimutu"] = dict(
    alt=["朝食暮吐"],
    hid=["早上吃的晚上吐", "吃了很久才吐"],
    definition="朝食暮吐。胃反（反胃）之候。",
    note="金匮要略·呕吐哕下利病：'朝食暮吐，暮食朝吐，宿谷不化，名曰胃反。'")
SYN["Ou"] = dict(
    alt=["呕"],
    hid=["呕", "干呕"],
    definition="呕吐。",
    note="伤寒论第96条：'心烦喜呕'。")
SYN["Weiou"] = dict(
    alt=["微呕"],
    hid=["有点想吐", "轻微恶心"],
    definition="轻微呕吐。",
    note="伤寒论第146条：'心下支结，外证未去者，柴胡桂枝汤主之。'")
SYN["Ganou"] = dict(
    alt=["干呕"],
    hid=["干呕", "干恶心", "干呕没东西"],
    definition="呕而无物。",
    note="伤寒论第12条：'鼻鸣干呕者，桂枝汤主之。'")
SYN["Tu"] = dict(
    alt=["吐"],
    hid=["吐", "吐东西"],
    definition="吐出胃内容物。",
    note="")
SYN["Yuou"] = dict(
    alt=["欲呕", "恶心"],
    hid=["恶心", "想吐", "恶心欲吐", "反胃"],
    definition="欲呕而未呕。",
    note="伤寒论第96条：'心烦喜呕'。")
SYN["Yutu"] = dict(
    alt=["欲吐"],
    hid=["要吐"],
    definition="欲吐。",
    note="伤寒论第282条：'少阴病，欲吐不吐。'")
SYN["Wenwenyutu"] = dict(
    alt=["温温欲吐"],
    hid=["心里泛泛想吐"],
    definition="温温然欲吐。",
    note="伤寒论第123条：'温温欲吐，复不能吐。'")
SYN["Buou"] = dict(
    alt=["不呕"],
    hid=["不吐", "没有恶心"],
    definition="不呕吐。",
    note="伤寒论第96条：'胸中烦而不呕者。'")
SYN["Hui"] = dict(
    alt=["哕", "呃逆"],
    hid=["打嗝", "呃逆", "打嗝不止"],
    definition="呃逆，气从胃中上逆有声。",
    note="金匮要略·呕吐哕下利病：'哕而腹满，视其前后，知何部不利，利之即愈。'")
SYN["Yiqi"] = dict(
    alt=["噫气", "嗳气"],
    hid=["打嗝", "嗳气", "打饱嗝"],
    definition="嗳气，胃中气上逆有声。",
    note="伤寒论第161条：'伤寒发汗，若吐若下，解后，心下痞硬，噫气不除者，旋覆代赭汤主之。'")
SYN["Aifu"] = dict(
    alt=["嗳腐", "噫气酸腐"],
    hid=["打嗝有酸腐味", "嗳腐气"],
    definition="嗳气酸腐。食积之候。",
    note="")
SYN["Ye"] = dict(
    alt=["噎"],
    hid=["噎住", "吞咽困难"],
    definition="吞咽哽噎。",
    note="金匮要略·呕吐哕下利病。")
SYN["Qini"] = dict(
    alt=["气逆"],
    hid=["气往上逆", "气逆"],
    definition="气机上逆。",
    note="")
SYN["Qishangchong"] = dict(
    alt=["气上冲"],
    hid=["气往上冲", "一股气往上顶"],
    definition="气从下上冲。",
    note="伤寒论第15条：'太阳病，下之后，其气上冲者，可与桂枝汤。'")
SYN["Qishangchongxiong"] = dict(
    alt=["气上冲胸"],
    hid=["气冲胸口"],
    definition="气上冲于胸。",
    note="伤寒论第67条：'心下逆满，气上冲胸，起则头眩。'")
SYN["Qishangchongxiongyan"] = dict(
    alt=["气上冲胸咽"],
    hid=["气冲胸咽"],
    definition="气上冲胸咽。",
    note="伤寒论第166条。")
SYN["Qicongshaofushangchongxin"] = dict(
    alt=["气从少腹上冲心"],
    hid=["气从小腹往上冲心"],
    definition="气从少腹上冲于心。奔豚之候。",
    note="金匮要略·奔豚气病：'奔豚病，从少腹起，上冲咽喉，发作欲死，复还止。'")
SYN["Qicongshaofushangchongxiongyan"] = dict(
    alt=["气从少腹上冲胸咽"],
    hid=["气从小腹冲胸咽"],
    definition="气从少腹上冲胸咽。奔豚之候。",
    note="金匮要略·奔豚气病。")
SYN["Ganyishichou"] = dict(
    alt=["干噫食臭"],
    hid=["打嗝有食物味"],
    definition="嗳气有食臭。",
    note="伤寒论第157条。")
SYN["Ji"] = dict(
    alt=["饥"],
    hid=["饿", "觉得饿"],
    definition="饥饿感。",
    note="")
SYN["Tunsuan"] = dict(
    alt=["吞酸", "吐酸"],
    hid=["反酸", "烧心", "泛酸", "胃里反酸"],
    definition="胃中酸水上泛。肝胃不和之候。",
    note="胡老：吞酸多属肝胃不和，左金丸、吴茱萸汤类。")
SYN["Shizetuhui"] = dict(
    alt=["食则吐蛔"],
    hid=["一吃东西就吐蛔虫"],
    definition="进食则吐蛔。",
    note="伤寒论第338条：'蛔厥者，乌梅丸主之。'")
SYN["Xiou"] = dict(
    alt=["喜呕"],
    hid=["容易恶心", "动不动就吐"],
    definition="经常呕吐。少阳之候。",
    note="伤寒论第96条：'心烦喜呕。'")
SYN["Tuli"] = dict(
    alt=["吐利"],
    hid=["又吐又拉"],
    definition="呕吐兼下利。",
    note="伤寒论第309条：'少阴病，吐利，手足逆冷，烦躁欲死者，吴茱萸汤主之。'")
SYN["Shirukoujitu"] = dict(
    alt=["食入口即吐"],
    hid=["一吃就吐", "吃进去马上吐"],
    definition="食入即吐。胃热之候。",
    note="金匮要略·呕吐哕下利病：'食已即吐者，大黄甘草汤主之。'")
SYN["Shiyijitu"] = dict(
    alt=["食已即吐"],
    hid=["吃完就吐"],
    definition="食后即吐。",
    note="金匮要略·呕吐哕下利病。")
SYN["Ouni"] = dict(
    alt=["呕逆"],
    hid=["呕逆", "恶心打嗝"],
    definition="呕逆。",
    note="")
SYN["Oujiabenke"] = dict(
    alt=["呕家本渴"],
    hid=["呕吐的人本来会渴"],
    definition="呕家本渴。",
    note="金匮要略·痰饮：'呕家本渴，渴者为欲解，今反不渴，心下有支饮故也。'")
SYN["Shiguyuou"] = dict(
    alt=["食谷欲呕"],
    hid=["一吃饭就想吐"],
    definition="食谷欲呕。阳明中寒之候。",
    note="伤寒论第243条：'食谷欲呕，属阳明也，吴茱萸汤主之。'")
SYN["Housishui"] = dict(
    alt=["后思水"],
    hid=["吐后想喝水"],
    definition="呕吐后思水。",
    note="金匮要略·呕吐哕下利病。")

# ========== 十、饮食类 ==========
SYN["Shibuxia"] = dict(
    alt=["食不下"],
    hid=["吃不下饭", "食欲差"],
    definition="饮食不下。太阴病提纲证之一。",
    note="伤寒论第273条：'太阴之为病，腹满而吐，食不下。'")
SYN["Buyushi"] = dict(
    alt=["不欲食", "不欲饮食"],
    hid=["没胃口", "食欲不振", "不想吃饭", "吃不下", "没食欲"],
    definition="不思饮食。少阳或太阴之候。",
    note="伤寒论第96条：'嘿嘿不欲饮食。'")
SYN["Nengshi"] = dict(
    alt=["能食"],
    hid=["能吃", "胃口好"],
    definition="能进食。",
    note="伤寒论第190条：'阳明病，若能食，名中风；不能食，名中寒。'")
SYN["Yinshirugu"] = dict(
    alt=["饮食如故"],
    hid=["饮食正常", "胃口跟平时一样"],
    definition="饮食如常。",
    note="金匮要略·妇人妊娠病：'妊娠呕吐不止，干姜人参半夏丸主之。'")
SYN["Bunengyinshi"] = dict(
    alt=["不能饮食"],
    hid=["不能吃", "吃不了东西"],
    definition="不能饮食。",
    note="金匮要略·腹满寒疝宿食。")
SYN["Yinshihuoyoumeishi"] = dict(
    alt=["饮食或有美时"],
    hid=["有时胃口好"],
    definition="饮食有时尚可。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Ewenshichou"] = dict(
    alt=["恶闻食臭"],
    hid=["闻到饭味就难受", "闻不得饭味"],
    definition="厌恶闻食物气味。",
    note="伤寒论第243条。")
SYN["Bunengshiyin"] = dict(
    alt=["不能食饮"],
    hid=["不能吃喝"],
    definition="不能饮食。",
    note="")
SYN["Sushi"] = dict(
    alt=["宿食"],
    hid=["积食", "吃多了不消化"],
    definition="宿食停滞。",
    note="金匮要略·腹满寒疝宿食：'宿食在上脘，当吐之，宜瓜蒂散。'")
SYN["Weizhongbuhe"] = dict(
    alt=["胃中不和"],
    hid=["胃不舒服", "胃里不调和"],
    definition="胃中不和。",
    note="伤寒论第158条。")
SYN["Weizhongyouxieqi"] = dict(
    alt=["胃中有邪气"],
    hid=["胃里有邪气"],
    definition="胃中有邪气。",
    note="伤寒论第173条。")
SYN["Xiaogushanji2"] = dict()  # 占位，避免误用
del SYN["Xiaogushanji2"]

# ========== 十一、手足四肢类 ==========
SYN["Shouzujueni"] = dict(
    alt=["手足厥逆", "四肢厥逆", "厥逆", "手足厥冷", "手足逆冷", "四肢逆冷"],
    hid=["手脚冰凉", "手脚冰冷", "四肢冰冷", "手脚冰"],
    definition="手足寒冷至肘膝。阴阳气不相顺接，厥阴病主症之一。",
    note="伤寒论第337条：'凡厥者，阴阳气不相顺接，便为厥。厥者，手足逆冷者是也。'胡老：厥有寒厥、热厥之分。")
SYN["Shouzunileng"] = dict(
    alt=["手足逆冷"],
    hid=[],
    definition="手足逆冷。",
    note="伤寒论第337条。")
SYN["Shouzuleng"] = dict(
    alt=["手足冷", "手足寒"],
    hid=["手脚冷", "手脚发凉", "手脚凉"],
    definition="手足发冷。",
    note="伤寒论第148条：'手足冷，心下满，口不欲食，大便硬，脉细者，此为阳微结。'")
SYN["Shouzuzaorao"] = dict(
    alt=["手足躁扰"],
    hid=["手脚乱动烦躁"],
    definition="手足躁扰不安。",
    note="伤寒论第114条。")
SYN["Shouzufanre"] = dict(
    alt=["手足烦热"],
    hid=["手脚心发热", "手脚烦热"],
    definition="手足烦热。虚劳或阴虚之候。",
    note="金匮要略·血痹虚劳：'手足烦热，咽干口燥，小建中汤主之。'")
SYN["Shouzhangfanre"] = dict(
    alt=["手掌烦热"],
    hid=["手心发热", "手心热"],
    definition="手掌烦热。",
    note="金匮要略·妇人杂病。")
SYN["Shouzuburen"] = dict(
    alt=["手足不仁"],
    hid=["手脚麻木", "手脚没知觉"],
    definition="手足麻木不仁。",
    note="伤寒论第174条。")
SYN["Sizhizhong"] = dict(
    alt=["四肢肿"],
    hid=["四肢肿", "手脚肿"],
    definition="四肢浮肿。",
    note="金匮要略·水气病。")
SYN["Sizhinieniedong"] = dict(
    alt=["四肢聂聂动"],
    hid=["四肢微微瞤动"],
    definition="四肢轻微瞤动。",
    note="金匮要略·痰饮。")
SYN["Sizhifanzhong"] = dict(
    alt=["四肢烦重"],
    hid=["四肢烦重"],
    definition="四肢烦热沉重。",
    note="")
SYN["Sizhichenzhongtengtong"] = dict(
    alt=["四肢沉重疼痛"],
    hid=["四肢又沉又重又疼"],
    definition="四肢沉重疼痛。",
    note="伤寒论第316条：'少阴病，二三日不已，至四五日，腹痛，小便不利，四肢沉重疼痛，自下利者……真武汤主之。'")
SYN["Jiaozhong"] = dict(
    alt=["脚肿"],
    hid=["腿肿", "脚肿", "下肢浮肿"],
    definition="脚部浮肿。",
    note="金匮要略·水气病。")
SYN["Jiaozhongrutuo"] = dict(
    alt=["脚肿如脱"],
    hid=["脚肿得像要掉下来"],
    definition="脚肿如脱。",
    note="金匮要略·中风历节病：'脚肿如脱，头眩短气，温温欲吐，桂枝芍药知母汤主之。'")
SYN["Zhuanjin"] = dict(
    alt=["转筋"],
    hid=["抽筋", "腿抽筋"],
    definition="筋脉拘挛抽搐。",
    note="金匮要略·趺蹶手指臂肿转筋阴狐疝蛔虫病：'转筋之为病，其人臂脚直，脉上下行，微弦。'")
SYN["Jiaoluanji"] = dict(
    alt=["脚挛急"],
    hid=["小腿抽筋", "脚抽筋"],
    definition="小腿拘挛急迫。",
    note="伤寒论第29条：'脚挛急……作芍药甘草汤与之，其脚即伸。'")
SYN["Sizhiweiji"] = dict(
    alt=["四肢微急"],
    hid=["四肢微微拘急"],
    definition="四肢轻微拘急。",
    note="伤寒论第20条：'四肢微急，难以屈伸者，桂枝加附子汤主之。'")
SYN["Sizhisuanteng"] = dict(
    alt=["四肢酸疼"],
    hid=["四肢酸痛", "浑身酸痛"],
    definition="四肢酸痛。",
    note="金匮要略·血痹虚劳：'四肢酸疼……小建中汤主之。'")
SYN["Jintirourun"] = dict(
    alt=["筋惕肉瞤"],
    hid=["肌肉跳动", "肉跳", "身上肉跳"],
    definition="筋肉跳动。阳虚水泛之候。",
    note="伤寒论第38条：'筋惕肉瞤，此为逆也。'")
SYN["Jinzhizetongju"] = dict(
    alt=["近之则痛剧"],
    hid=["靠近就疼得厉害", "一碰就疼得厉害"],
    definition="近之则痛剧。",
    note="金匮要略·中风历节病。")
SYN["Xijingtengfan"] = dict(
    alt=["膝胫疼烦"],
    hid=["膝盖小腿又疼又烦"],
    definition="膝胫疼痛烦扰。",
    note="金匮要略·中风历节病。")
SYN["Zuhan"] = dict(
    alt=["足寒"],
    hid=["脚冷", "脚发凉"],
    definition="足部寒冷。",
    note="")
SYN["Danbibusui"] = dict(
    alt=["但臂不遂"],
    hid=["胳膊不能动", "一只胳膊不遂"],
    definition="单臂不能随意运动。",
    note="金匮要略·中风历节病：'但臂不遂者，此为痹。'")
SYN["Liangjingzileng"] = dict(
    alt=["两胫自冷"],
    hid=["两条小腿发冷"],
    definition="两小腿自觉寒冷。",
    note="金匮要略·血痹虚劳。")
SYN["Zuxiare"] = dict(
    alt=["足下热"],
    hid=["脚心发热", "脚底热"],
    definition="足下发热。阴虚或湿热下注。",
    note="金匮要略·黄疸病。")
SYN["Shouzujuji"] = dict(
    alt=["手足拘急"],
    hid=["手脚拘紧", "手脚抽筋"],
    definition="手足拘急。",
    note="")
SYN["Sizhinileng"] = dict(
    alt=["四肢逆冷"],
    hid=["四肢冰冷", "手脚冰凉"],
    definition="四肢逆冷。",
    note="伤寒论第337条。")
SYN["Shouzujueleng"] = dict(
    alt=["手足厥冷"],
    hid=["手脚冰冷", "手脚冰凉"],
    definition="手足厥冷。",
    note="伤寒论第337条。")
SYN["WeiHan"] = dict(
    alt=["畏寒"],
    hid=["怕冷", "畏寒"],
    definition="畏寒怕冷。",
    note="")
SYN["Renbijiaozhi"] = dict(
    alt=["臂脚直"],
    hid=["胳膊腿发直"],
    definition="臂脚强直。",
    note="金匮要略·趺蹶手指臂肿转筋阴狐疝蛔虫病。")

# ========== 十二、身体躯干类 ==========
SYN["Shentong"] = dict(
    alt=["身痛", "身疼痛", "身体疼痛", "一身尽疼"],
    hid=["浑身疼", "全身酸痛", "身上疼", "浑身酸痛"],
    definition="身体疼痛。",
    note="伤寒论第35条：'身疼痛……麻黄汤主之。'胡老：身痛为表实，宜发汗。")
SYN["Shentengfan"] = dict(
    alt=["身疼烦"],
    hid=["浑身疼又烦"],
    definition="身疼痛而烦。",
    note="")
SYN["Shentizhong"] = dict(
    alt=["身体肿"],
    hid=["身上肿", "全身浮肿"],
    definition="身体浮肿。",
    note="金匮要略·水气病。")
SYN["Shentiburen"] = dict(
    alt=["身体不仁"],
    hid=["身上麻木", "身体没知觉"],
    definition="身体麻木不仁。",
    note="金匮要略·血痹虚劳：'身体不仁，如风痹状，黄芪桂枝五物汤主之。'")
SYN["Shentiwanglei"] = dict(
    alt=["身体尪羸"],
    hid=["身体瘦弱畸形"],
    definition="身体瘦弱。",
    note="金匮要略·中风历节病。")
SYN["Shenzhong"] = dict(
    alt=["身重"],
    hid=["身上沉", "身体沉重", "浑身发沉"],
    definition="身体沉重。湿盛或阳虚。",
    note="伤寒论第49条：'身重，心悸。'")
SYN["Shenrundong"] = dict(
    alt=["身瞤动"],
    hid=["身上肉跳", "身体肌肉跳动"],
    definition="身体肌肉跳动。",
    note="伤寒论第82条：'太阳病发汗，汗出不解，其人仍发热，心下悸，头眩，身瞤动，振振欲擗地者，真武汤主之。'")
SYN["Shenhuang"] = dict(
    alt=["身黄"],
    hid=["全身发黄", "身上黄"],
    definition="全身发黄。黄疸之候。",
    note="金匮要略·黄疸病。")
SYN["Zhuhuang"] = dict(
    alt=["诸黄"],
    hid=["各种黄疸"],
    definition="各种黄疸。",
    note="金匮要略·黄疸病。")
SYN["Shenduohan"] = dict(
    alt=["身多寒"],
    hid=["身上多寒"],
    definition="身体多寒。",
    note="")
SYN["Shenghouzhe"] = dict(
    alt=["生后者"],
    hid=["产后之人"],
    definition="产后之人。",
    note="")
SYN["Shentibunengzishouchi"] = dict(
    alt=["身体不能自收持"],
    hid=["身体不能自控"],
    definition="身体不能自主收持。",
    note="金匮要略·五脏风寒积聚病。")
SYN["Nanyizhuance"] = dict(
    alt=["难以转侧"],
    hid=["翻身困难", "转身困难"],
    definition="身体难以转侧。",
    note="伤寒论第107条：'胸满烦惊，小便不利，谵语，一身尽重，不可转侧者，柴胡加龙骨牡蛎汤主之。'")
SYN["Yishenjinzhong"] = dict(
    alt=["一身尽重"],
    hid=["浑身沉重"],
    definition="全身沉重。",
    note="伤寒论第107条。")
SYN["Shenruchongxingpizhong"] = dict(
    alt=["身如虫行皮中"],
    hid=["身上像有虫爬"],
    definition="身如虫行皮中。",
    note="伤寒论第196条：'阳明病，法多汗，反无汗，其身如虫行皮中状者，此以久虚故也。'")
SYN["Pifusuqi"] = dict(
    alt=["皮肤粟起"],
    hid=["起鸡皮疙瘩"],
    definition="皮肤起粟粒。",
    note="")
SYN["Xingtisunfen"] = dict(
    alt=["形体损分"],
    hid=["形体消瘦"],
    definition="形体消瘦。",
    note="")
SYN["Shenxingruhe"] = dict(
    alt=["身形如和"],
    hid=["身形如常"],
    definition="身形如常。",
    note="")
SYN["Shenyang"] = dict(
    alt=["身痒"],
    hid=["身上痒", "浑身痒", "皮肤痒"],
    definition="身体瘙痒。表郁或风湿。",
    note="伤寒论第23条：'以其不能得小汗出，身必痒，宜桂枝麻黄各半汤。'")
SYN["Jifuburen"] = dict(
    alt=["肌肤不仁"],
    hid=["皮肤麻木", "肌肤无知觉"],
    definition="肌肤麻木不仁。",
    note="金匮要略·中风历节病。")
SYN["Huoyinyaoji"] = dict(
    alt=["或引腰脊"],
    hid=["牵引腰脊"],
    definition="疼痛牵引腰脊。",
    note="")
SYN["Shenweizhong"] = dict(
    alt=["身微肿"],
    hid=["身上微肿"],
    definition="身体轻微浮肿。",
    note="")
SYN["Yishenjinteng"] = dict(
    alt=["一身尽疼"],
    hid=["浑身都疼"],
    definition="全身疼痛。",
    note="金匮要略·痉湿暍病：'湿家身烦疼，可与麻黄加术汤。'")
SYN["ShenTengtong"] = dict(
    alt=["身疼痛"],
    hid=["浑身疼", "全身疼痛"],
    definition="身体疼痛。",
    note="伤寒论第35条。")
SYN["Jifujiacuo"] = dict(
    alt=["肌肤甲错"],
    hid=["皮肤粗糙像鱼鳞", "肌肤干糙"],
    definition="肌肤粗糙如鳞甲交错。内有干血之候。",
    note="金匮要略·血痹虚劳：'内有干血，肌肤甲错，两目黯黑，缓中补虚，大黄蟅虫丸主之。'")
SYN["Liangmuanhei"] = dict(
    alt=["两目黯黑"],
    hid=["两眼发暗发黑"],
    definition="两目周围黯黑。瘀血之候。",
    note="金匮要略·血痹虚劳。")
SYN["Juanwo"] = dict(
    alt=["倦卧"],
    hid=["蜷着睡", "倦卧"],
    definition="倦卧。",
    note="")
SYN["Shiwo"] = dict(
    alt=["嗜卧"],
    hid=["爱躺着", "总想躺着"],
    definition="嗜睡喜卧。",
    note="")
SYN["Jingshenweimi"] = dict(
    alt=["精神萎靡"],
    hid=["没精神", "精神差", "萎靡不振"],
    definition="精神萎靡不振。",
    note="")

# ========== 十三、关节骨节类 ==========
SYN["Gujietong"] = dict(
    alt=["骨节痛", "骨节疼痛", "百节疼痛"],
    hid=["关节疼", "骨头疼", "全身关节痛"],
    definition="骨节疼痛。",
    note="伤寒论第35条：'骨节疼痛……麻黄汤主之。'")
SYN["Gujietengfan"] = dict(
    alt=["骨节疼烦"],
    hid=["关节疼又烦"],
    definition="骨节疼痛而烦。",
    note="金匮要略·痉湿暍病。")
SYN["Zhijietong"] = dict(
    alt=["肢节痛"],
    hid=["肢节疼痛"],
    definition="肢节疼痛。",
    note="")
SYN["Guanjietengtong"] = dict(
    alt=["关节疼痛"],
    hid=["关节疼", "关节痛"],
    definition="关节疼痛。",
    note="")
SYN["Zhuzhijietengtong"] = dict(
    alt=["诸肢节疼痛"],
    hid=["全身关节疼痛"],
    definition="诸肢节疼痛。",
    note="金匮要略·中风历节病：'诸肢节疼痛，身体尪羸，脚肿如脱，头眩短气……桂枝芍药知母汤主之。'")
SYN["Chetongbudequshen"] = dict(
    alt=["掣痛不得屈伸"],
    hid=["抽掣疼不能屈伸"],
    definition="掣痛不得屈伸。",
    note="金匮要略·痉湿暍病。")
SYN["Bukequshen"] = dict(
    alt=["不可屈伸"],
    hid=["不能屈伸", "伸不直"],
    definition="肢体不可屈伸。",
    note="伤寒论第20条。")
SYN["Yaotong"] = dict(
    alt=["腰痛"],
    hid=["腰疼", "腰痛"],
    definition="腰部疼痛。",
    note="金匮要略·血痹虚劳：'虚劳腰痛，少腹拘急，小便不利者，八味肾气丸主之。'")
SYN["Yaozhongleng"] = dict(
    alt=["腰中冷"],
    hid=["腰发冷", "腰凉"],
    definition="腰中寒冷。",
    note="金匮要略·五脏风寒积聚病：'肾着之病，其人身体重，腰中冷，如坐水中。'")
SYN["Yaoyixiayoushuiqi"] = dict(
    alt=["腰以下有水气"],
    hid=["腰以下水肿"],
    definition="腰以下有水气。",
    note="金匮要略·水气病。")
SYN["Sizhilijietong"] = dict(
    alt=["四肢历节痛"],
    hid=["四肢关节疼痛"],
    definition="四肢历节疼痛。",
    note="金匮要略·中风历节病。")
SYN["Baijietengtong"] = dict(
    alt=["百节疼痛"],
    hid=["全身关节疼痛"],
    definition="百节疼痛。",
    note="")
SYN["Gujietengtong"] = dict(
    alt=["骨节疼痛"],
    hid=["关节疼", "骨节疼"],
    definition="骨节疼痛。",
    note="伤寒论第35条。")
SYN["Rufengbizhuang"] = dict(
    alt=["如风痹状"],
    hid=["像风痹一样"],
    definition="如风痹之状。",
    note="金匮要略·血痹虚劳。")
SYN["Ruzuoshuizhong"] = dict(
    alt=["如坐水中"],
    hid=["像坐在水里"],
    definition="如坐水中。肾着之候。",
    note="金匮要略·五脏风寒积聚病：'肾着之病……腰以下冷痛，腹重如带五千钱。'")

# ========== 十四、神志类 ==========
SYN["Zhanyu"] = dict(
    alt=["谵语"],
    hid=["说胡话", "胡言乱语", "神志不清说胡话"],
    definition="神志不清，语无伦次。阳明腑实热盛之候。",
    note="伤寒论第210条：'夫实则谵语，虚则郑声。'胡老：谵语多属阳明里实。")
SYN["Rukuang"] = dict(
    alt=["如狂"],
    hid=["像发狂一样", "烦躁得像疯了"],
    definition="如狂之状。瘀血或热结之候。",
    note="伤寒论第106条：'其人如狂，血自下，下者愈。'")
SYN["Jing"] = dict(
    alt=["惊", "惊悸"],
    hid=["容易受惊", "一惊一乍", "胆小易惊"],
    definition="惊惕不安。",
    note="伤寒论第107条：'胸满烦惊。'")
SYN["Jingkuang"] = dict(
    alt=["惊狂"],
    hid=["惊狂", "又惊又狂"],
    definition="惊狂不安。",
    note="伤寒论第112条：'伤寒脉浮，医以火迫劫之，亡阳，必惊狂，卧起不安者，桂枝去芍药加蜀漆牡蛎龙骨救逆汤主之。'")
SYN["Kong"] = dict(
    alt=["恐"],
    hid=["恐惧", "害怕"],
    definition="恐惧不安。",
    note="")
SYN["Mengjiao"] = dict(
    alt=["梦交"],
    hid=["梦中交合"],
    definition="梦中交合。",
    note="金匮要略·血痹虚劳：'脉得诸芤动微紧，男子失精，女子梦交，桂枝加龙骨牡蛎汤主之。'")
SYN["Beishang"] = dict(
    alt=["悲伤"],
    hid=["悲伤", "爱哭"],
    definition="悲伤欲哭。",
    note="金匮要略·妇人杂病：'妇人脏躁，喜悲伤欲哭，象如神灵所作，数欠伸，甘麦大枣汤主之。'")
SYN["Xibeishangyuku"] = dict(
    alt=["喜悲伤欲哭"],
    hid=["老想哭", "动不动就哭"],
    definition="喜悲伤欲哭。脏躁之候。",
    note="金匮要略·妇人杂病。")
SYN["Xiangrushenlingsuozuo"] = dict(
    alt=["象如神灵所作"],
    hid=["像有神灵附体"],
    definition="状如神灵所作。脏躁之候。",
    note="金匮要略·妇人杂病。")
SYN["Shantaixi"] = dict(
    alt=["善太息"],
    hid=["爱叹气", "老叹气"],
    definition="频频叹息。肝郁之候。",
    note="金匮要略·妇人杂病。")
SYN["Danyumei"] = dict(
    alt=["但欲寐", "嗜卧", "倦卧"],
    hid=["总想睡觉", "没精神", "老想睡", "精神萎靡", "昏昏欲睡"],
    definition="精神萎靡，但欲睡眠。少阴病提纲证之一。",
    note="伤寒论第281条：'少阴之为病，脉微细，但欲寐也。'胡老：但欲寐为少阴第一主症。")
SYN["Budewo"] = dict(
    alt=["不得卧"],
    hid=["躺不住", "不能平躺", "不能躺下", "平躺就难受"],
    definition="不能安卧。",
    note="金匮要略·痰饮：'咳逆倚息，短气不得卧，其形如肿，谓之支饮。'")
SYN["Budemian"] = dict(
    alt=["不得眠", "失眠"],
    hid=["睡不着", "失眠", "难以入睡", "睡不着觉"],
    definition="不能入睡。",
    note="伤寒论第76条：'虚烦不得眠……栀子豉汤主之。'")
SYN["Budeyu"] = dict(
    alt=["不得语"],
    hid=["不能说话"],
    definition="不能言语。",
    note="")
SYN["Woqibuan"] = dict(
    alt=["卧起不安"],
    hid=["躺下起来都不安"],
    definition="卧起不安。",
    note="伤寒论第112条。")
SYN["Xufan"] = dict(
    alt=["虚烦"],
    hid=["心里烦得慌", "虚烦"],
    definition="虚烦不眠。热扰胸膈之候。",
    note="伤寒论第76条：'虚烦不得眠……栀子豉汤主之。'")
SYN["Momo"] = dict(
    alt=["嘿嘿", "默默"],
    hid=["闷闷不乐", "不爱说话"],
    definition="嘿嘿然沉默不语。少阳之候。",
    note="伤寒论第96条：'嘿嘿不欲饮食。'")
SYN["Shuqianshen"] = dict(
    alt=["数欠伸"],
    hid=["老打哈欠伸懒腰"],
    definition="频频欠伸。脏躁之候。",
    note="金匮要略·妇人杂病。")
SYN["Wangxing"] = dict(
    alt=["妄行"],
    hid=["行为失常"],
    definition="行为妄动。",
    note="")
SYN["Duyubuxiu"] = dict(
    alt=["独语不休"],
    hid=["自言自语不停"],
    definition="独语不休。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Fakuang"] = dict(
    alt=["发狂"],
    hid=["发狂", "疯了似的"],
    definition="发狂躁动。阳明热盛或瘀血。",
    note="伤寒论第124条：'其人发狂者，以热在下焦。'")
SYN["Shanwang"] = dict(
    alt=["善忘"],
    hid=["健忘", "记性差"],
    definition="健忘。瘀血或虚劳之候。",
    note="伤寒论第237条：'其人喜忘者，必有蓄血。'")
SYN["Zhengsheng"] = dict(
    alt=["郑声"],
    hid=["声音低微重复"],
    definition="郑声，语言重复而声低。虚证之候。",
    note="伤寒论第210条：'虚则郑声。郑声者，重语也。'")
SYN["Xunyimochuang"] = dict(
    alt=["循衣摸床"],
    hid=["手乱摸衣被床"],
    definition="循衣摸床。神昏之危候。",
    note="伤寒论第212条：'循衣摸床，惕而不安。'")
SYN["Tierbuan"] = dict(
    alt=["惕而不安"],
    hid=["惊惕不安"],
    definition="惊惕不安。",
    note="伤寒论第212条。")
SYN["Zhenzhenyupidi"] = dict(
    alt=["振振欲擗地"],
    hid=["摇摇晃晃要倒地"],
    definition="振振欲仆地。阳虚水泛之候。",
    note="伤寒论第82条：'身瞤动，振振欲擗地者，真武汤主之。'")
SYN["Shenweizhenzhenyao"] = dict(
    alt=["身为振振摇"],
    hid=["身体摇晃"],
    definition="身体振摇。",
    note="伤寒论第67条：'身为振振摇者，茯苓桂枝白术甘草汤主之。'")
SYN["Chashouzimaoxin"] = dict(
    alt=["叉手自冒心"],
    hid=["双手交叉按心口"],
    definition="叉手自按心口。心虚之候。",
    note="伤寒论第64条：'发汗过多，其人叉手自冒心，心下悸，欲得按者，桂枝甘草汤主之。'")
SYN["Yudean"] = dict(
    alt=["欲得按"],
    hid=["想让人按", "按着舒服"],
    definition="欲得按压。虚证之候。",
    note="伤寒论第64条。")
SYN["Rujianguizhuang"] = dict(
    alt=["如见鬼状"],
    hid=["像看见鬼一样"],
    definition="如见鬼状。热盛神昏之候。",
    note="伤寒论第212条：'独语如见鬼状。'")
SYN["Duomianshui"] = dict(
    alt=["多眠睡"],
    hid=["老想睡"],
    definition="多眠睡。",
    note="伤寒论第6条：'风温为病……多眠睡，鼻息必鼾。'")
SYN["Bixibihan"] = dict(
    alt=["鼻息必鼾"],
    hid=["打鼾", "睡觉打呼"],
    definition="鼻息鼾声。",
    note="伤寒论第6条。")
SYN["Zhishi"] = dict(
    alt=["直视"],
    hid=["两眼发直", "眼睛直视"],
    definition="两目直视。神昏之危候。",
    note="伤寒论第210条：'直视谵语，喘满者死。'")
SYN["Shisou"] = dict(
    alt=["失溲"],
    hid=["大小便失禁"],
    definition="大小便失禁。",
    note="伤寒论第6条。")
SYN["Chizong"] = dict(
    alt=["瘛疭"],
    hid=["抽搐", "手脚抽搐"],
    definition="手足抽搐。",
    note="伤寒论第6条。")
SYN["Zhenzhenshenrunju"] = dict(
    alt=["振振身瞤剧"],
    hid=["浑身抖动肉跳厉害"],
    definition="振振身瞤动剧烈。",
    note="金匮要略·痰饮。")
SYN["Momoyumian"] = dict(
    alt=["默默欲眠"],
    hid=["默默想睡"],
    definition="默默欲眠。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Mubudebi"] = dict(
    alt=["目不得闭"],
    hid=["眼睛闭不上"],
    definition="目不得闭。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Mianmuzhachizhaheizhabai"] = dict(
    alt=["面目乍赤乍黑乍白"],
    hid=["脸色忽红忽黑忽白"],
    definition="面目忽赤忽黑忽白。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Yanhuxuanmao"] = dict(
    alt=["奄忽眩冒"],
    hid=["突然眩晕昏冒"],
    definition="忽然眩冒。",
    note="金匮要略·妇人杂病。")
SYN["Zhuangrujuedian"] = dict(
    alt=["状如厥癫"],
    hid=["像昏厥癫痫一样"],
    definition="状如厥癫。",
    note="金匮要略·妇人杂病。")
SYN["Wozejing"] = dict(
    alt=["卧则惊"],
    hid=["一躺下就惊"],
    definition="卧则惊惕。",
    note="")
SYN["Yanyujianse"] = dict(
    alt=["言语謇涩"],
    hid=["说话不利索", "言语不清"],
    definition="言语謇涩不利。",
    note="")
SYN["Bunengqi"] = dict(
    alt=["不能起"],
    hid=["起不来"],
    definition="不能起立。",
    note="")
SYN["Yiyushifubunengshi"] = dict(
    alt=["意欲食复不能食"],
    hid=["想吃又吃不下"],
    definition="意欲食而复不能食。百合病之候。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Changmoran"] = dict(
    alt=["常默然"],
    hid=["常常沉默不语"],
    definition="常默然不语。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Yuwobunengwo"] = dict(
    alt=["欲卧不能卧"],
    hid=["想躺又躺不住"],
    definition="欲卧不能卧。百合病之候。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Yuxingbunengxing"] = dict(
    alt=["欲行不能行"],
    hid=["想走又走不动"],
    definition="欲行不能行。百合病之候。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Ruhanwuhan"] = dict(
    alt=["如寒无寒"],
    hid=["像冷又不冷"],
    definition="如寒而无寒。百合病之候。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Rurewure"] = dict(
    alt=["如热无热"],
    hid=["像热又不热"],
    definition="如热而无热。百合病之候。",
    note="金匮要略·百合狐惑阴阳毒。")
SYN["Nishitoutong"] = dict(
    alt=["溺时头痛"],
    hid=["小便时头疼"],
    definition="溺时头痛。",
    note="金匮要略·消渴小便不利淋病。")
SYN["Fazehanre"] = dict(
    alt=["发则寒热"],
    hid=["发作时寒热"],
    definition="发作时寒热。",
    note="")
SYN["Fanluan"] = dict(
    alt=["烦乱"],
    hid=["心烦意乱"],
    definition="心烦意乱。",
    note="")
SYN["Kujizhiyuandi"] = dict(
    alt=["苦极"],
    hid=["痛苦至极"],
    definition="苦极。",
    note="")
SYN["Rukuangzhuang"] = dict(
    alt=["如狂状"],
    hid=["像发狂的样子"],
    definition="如狂之状。",
    note="")
SYN["Xiongzhongkui"] = dict(
    alt=["胸中愦"],
    hid=["胸中昏乱"],
    definition="胸中愦乱。",
    note="")
SYN["Miansewuhua"] = dict(
    alt=["面色无华"],
    hid=["脸色没光泽", "面色差"],
    definition="面色无华。",
    note="")
SYN["Sizhikufanre"] = dict(
    alt=["四肢苦烦热"],
    hid=["四肢烦热难受"],
    definition="四肢苦于烦热。",
    note="")
SYN["Zhubuzu"] = dict(
    alt=["诸不足"],
    hid=["各种虚损"],
    definition="诸般不足。虚劳之候。",
    note="金匮要略·血痹虚劳：'虚劳诸不足，风气百疾，薯蓣丸主之。'")
SYN["Fengqibaiji"] = dict(
    alt=["风气百疾"],
    hid=["风气各种病"],
    definition="风气百疾。",
    note="金匮要略·血痹虚劳。")
SYN["Xinqibuzu"] = dict(
    alt=["心气不足"],
    hid=["心气不足"],
    definition="心气不足。",
    note="")
SYN["Dabingchaihou"] = dict(
    alt=["大病差后"],
    hid=["大病初愈"],
    definition="大病瘥后。",
    note="伤寒论第393条：'大病差后，劳复者，枳实栀子豉汤主之。'")
SYN["Laofu"] = dict(
    alt=["劳复"],
    hid=["劳累后复发"],
    definition="劳复。",
    note="伤寒论第393条。")
SYN["Ribusuoju"] = dict(
    alt=["日晡所剧"],
    hid=["下午加重"],
    definition="日晡时加剧。",
    note="金匮要略·痉湿暍病：'风湿相搏……日晡所剧者，名风湿。'")
SYN["Xiongxiemanweijie"] = dict(
    alt=["胸胁满微结"],
    hid=["胸胁胀满微结"],
    definition="胸胁满而微结。",
    note="伤寒论第147条：'伤寒五六日，已发汗而复下之，胸胁满微结，小便不利，渴而不呕，但头汗出，往来寒热，心烦者，此为未解也，柴胡桂枝干姜汤主之。'")
SYN["Shanghanmaifu"] = dict(
    alt=["伤寒脉浮"],
    hid=["伤寒脉浮"],
    definition="伤寒脉浮。",
    note="")
SYN["Shuizhiweibing"] = dict(
    alt=["水之为病"],
    hid=["水气病"],
    definition="水气为病。",
    note="金匮要略·水气病。")
SYN["Xinxiayouzhiyin"] = dict(
    alt=["心下有支饮"],
    hid=["心下有支饮"],
    definition="心下有支饮。",
    note="金匮要略·痰饮。")
SYN["Kumaoxuan"] = dict(
    alt=["苦冒眩"],
    hid=["眩晕得厉害"],
    definition="苦于冒眩。支饮之候。",
    note="金匮要略·痰饮：'心下有支饮，其人苦冒眩，泽泻汤主之。'")
SYN["Fengshuiefeng"] = dict(
    alt=["风水恶风"],
    hid=["风水恶风"],
    definition="风水恶风。",
    note="金匮要略·水气病。")
SYN["Yuzuobentun"] = dict(
    alt=["欲作奔豚"],
    hid=["要发奔豚"],
    definition="欲作奔豚。",
    note="伤寒论第65条：'发汗后，其人脐下悸者，欲作奔豚。'")
SYN["Wurezheng"] = dict(
    alt=["无热证"],
    hid=["没有热象"],
    definition="无热证。",
    note="")
SYN["Hanqijueni"] = dict(
    alt=["寒气厥逆"],
    hid=["寒气厥逆"],
    definition="寒气厥逆。",
    note="")
SYN["Hanshanraoqitong"] = dict(
    alt=["寒疝绕脐痛"],
    hid=["寒疝绕脐痛"],
    definition="寒疝绕脐痛。",
    note="金匮要略·腹满寒疝宿食。")
SYN["Hanshanfutong"] = dict(
    alt=["寒疝腹痛"],
    hid=["寒疝腹痛"],
    definition="寒疝腹痛。",
    note="金匮要略·腹满寒疝宿食。")
SYN["Gejianzhiyin"] = dict(
    alt=["膈间支饮"],
    hid=["膈间支饮"],
    definition="膈间支饮。",
    note="金匮要略·痰饮。")
SYN["Gejianyoushui"] = dict(
    alt=["膈间有水"],
    hid=["膈间有水"],
    definition="膈间有水。",
    note="金匮要略·痰饮。")
SYN["Duotuokouzao"] = dict(
    alt=["多唾口燥"],
    hid=["多唾沫口干燥"],
    definition="多唾而口燥。",
    note="金匮要略·痰饮。")
SYN["Jueni"] = dict(
    alt=["厥逆"],
    hid=["厥逆", "四肢厥冷"],
    definition="厥逆。",
    note="伤寒论第337条。")
SYN["Fahan"] = dict(
    alt=["发寒"],
    hid=["发冷"],
    definition="发寒。",
    note="")
SYN["Wangxue"] = dict(
    alt=["亡血"],
    hid=["失血过多", "大出血"],
    definition="亡血，津血耗竭。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病。")
SYN["Lizhi"] = dict(
    alt=["利止"],
    hid=["拉肚子停了"],
    definition="下利突然停止。",
    note="伤寒论第385条：'恶寒脉微而复利，利止亡血也，四逆加人参汤主之。'")
SYN["Zaoshi"] = dict(
    alt=["燥屎"],
    hid=["燥屎", "干硬粪块"],
    definition="燥屎内结。阳明腑实之候。",
    note="伤寒论第209条：'转失气者，此有燥屎也。'")
SYN["Zhiyinxiongman"] = dict(
    alt=["支饮胸满"],
    hid=["支饮胸满"],
    definition="支饮胸满。",
    note="金匮要略·痰饮。")
SYN["Chanhouzhongfeng"] = dict(
    alt=["产后中风"],
    hid=["产后中风"],
    definition="产后中风。",
    note="金匮要略·妇人产后病。")
SYN["Jinchuang"] = dict(
    alt=["金疮"],
    hid=["刀伤", "外伤"],
    definition="金疮，金属所伤。",
    note="金匮要略·疮痈肠痈浸淫病。")
SYN["Jinyinchuang"] = dict(
    alt=["浸淫疮"],
    hid=["浸淫疮", "湿疹流水"],
    definition="浸淫疮，湿热浸淫。",
    note="金匮要略·疮痈肠痈浸淫病：'浸淫疮，从口流向四肢者可治。'")
SYN["Huichong"] = dict(
    alt=["蛔虫"],
    hid=["蛔虫", "肚子里有虫"],
    definition="蛔虫。",
    note="伤寒论第338条。")
SYN["Xintongfazuoyoushi"] = dict(
    alt=["心痛发作有时"],
    hid=["心痛定时发作"],
    definition="心痛发作有时。",
    note="")
SYN["Xinzhongpiqi"] = dict(
    alt=["心中痞气"],
    hid=["心中痞气"],
    definition="心中痞气。",
    note="金匮要略·胸痹心痛短气病。")
SYN["Dafeng"] = dict(
    alt=["大风"],
    hid=["大风"],
    definition="大风。",
    note="金匮要略·中风历节病。")
SYN["Churetanxian"] = dict(
    alt=["除热瘫痫"],
    hid=["除热瘫痫"],
    definition="除热瘫痫。",
    note="")
SYN["Darupan"] = dict(
    alt=["大如盘"],
    hid=["大如盘"],
    definition="心下坚大如盘。",
    note="金匮要略·水气病。")
SYN["Bianruxuanpan"] = dict(
    alt=["边如旋盘"],
    hid=["边如旋盘"],
    definition="边如旋盘。",
    note="金匮要略·水气病。")
SYN["Maibuchuzhe"] = dict(
    alt=["脉不出"],
    hid=["摸不到脉"],
    definition="脉不出。",
    note="伤寒论第301条。")
SYN["Qidongzhe"] = dict(
    alt=["脐上筑"],
    hid=["脐上跳动"],
    definition="脐上筑动。",
    note="金匮要略·奔豚气病。")
SYN["Weili"] = dict(
    alt=["微利"],
    hid=["稍微拉肚子"],
    definition="微利。",
    note="伤寒论第315条。")
SYN["Xiayouchenhan"] = dict(
    alt=["下有陈寒"],
    hid=["下焦有陈寒"],
    definition="下有陈寒。",
    note="金匮要略·妇人杂病。")
SYN["Xinxiaodutong"] = dict(
    alt=["心下毒痛"],
    hid=["心下剧痛"],
    definition="心下剧痛。",
    note="金匮要略·妇人妊娠病。")
SYN["Xuanji"] = dict(
    alt=["眩悸"],
    hid=["头晕心跳"],
    definition="眩冒心悸。",
    note="金匮要略·痰饮。")
SYN["Ziliyishen"] = dict(
    alt=["自利益甚"],
    hid=["拉肚子越来越重"],
    definition="自利益甚。太阴病提纲证之一。",
    note="伤寒论第273条。")
SYN["Wanguobuhua"] = dict(
    alt=["完谷不化"],
    hid=["拉不消化食物"],
    definition="完谷不化。",
    note="伤寒论第273条。")
SYN["Fumantong"] = dict(
    alt=["腹满痛"],
    hid=["肚子又胀又痛"],
    definition="腹满而痛。",
    note="")
SYN["FumanJuAn"] = dict(
    alt=["腹满拒按"],
    hid=["肚子胀按着疼"],
    definition="腹满拒按。",
    note="")
SYN["Momobuyushiyin"] = dict(
    alt=["默默不欲饮食"],
    hid=["闷闷不想吃饭"],
    definition="默默不欲饮食。少阳之候。",
    note="伤寒论第96条。")
SYN["Qishangzhuangxin"] = dict(
    alt=["气上撞心"],
    hid=["气往上撞心"],
    definition="气上撞心。厥阴病提纲证之一。",
    note="伤寒论第326条：'厥阴之为病，消渴，气上撞心，心中疼热，饥而不欲食，食则吐蛔。'")
SYN["Ripuchaore"] = dict(
    alt=["日晡潮热"],
    hid=["下午定时发热"],
    definition="日晡潮热。阳明腑实之候。",
    note="伤寒论第208条。")
SYN["Reli"] = dict(
    alt=["热利"],
    hid=["热性腹泻", "拉肚子发热"],
    definition="热利。",
    note="伤寒论第371条：'热利下重者，白头翁汤主之。'")
SYN["HanreWanglai"] = dict(
    alt=["寒热往来"],
    hid=["忽冷忽热"],
    definition="寒热往来。少阳之候。",
    note="伤寒论第96条。")
SYN["Xiuzuoyoushi"] = dict(
    alt=["休作有时"],
    hid=["定时发作"],
    definition="休作有时。",
    note="伤寒论第96条。")
SYN["Hanxiang"] = dict(
    alt=["寒象"],
    hid=["寒象"],
    definition="寒象。",
    note="")
SYN["Xiaobian"] = dict(
    alt=["小便"],
    hid=["小便"],
    definition="小便。",
    note="")

# ========== 十五、痉病类 ==========
SYN["Jingbing"] = dict(
    alt=["痉", "痉病", "刚痉", "柔痉"],
    hid=["抽搐", "抽风", "角弓反张"],
    definition="项背强急、口噤、背反张之病。太阳病发汗过多或风邪伤津所致。",
    note="金匮要略·痉湿暍病：'病者身热足寒，颈项强急，恶寒，时头热，面赤目赤，独头动摇，卒口噤，背反张者，痉病也。'")
SYN["Jingxiangqiangji"] = dict(
    alt=["颈项强急"],
    hid=["脖子僵硬拘急"],
    definition="颈项强直拘急。痉病之候。",
    note="金匮要略·痉湿暍病。")
SYN["Shitoure"] = dict(
    alt=["时头热"],
    hid=["头部时热"],
    definition="头部时时发热。痉病之候。",
    note="金匮要略·痉湿暍病。")
SYN["Dutoudongyao"] = dict(
    alt=["独头动摇"],
    hid=["头独自摇动"],
    definition="头部独自动摇。痉病之候。",
    note="金匮要略·痉湿暍病。")
SYN["Zukoujin"] = dict(
    alt=["卒口噤"],
    hid=["突然牙关紧闭"],
    definition="突然口噤不开。痉病之候。",
    note="金匮要略·痉湿暍病。")
SYN["Beifanzhang"] = dict(
    alt=["背反张"],
    hid=["角弓反张", "身体反弓"],
    definition="背部反张如弓。痉病之候。",
    note="金匮要略·痉湿暍病。")
SYN["Wobuzhexi"] = dict(
    alt=["卧不着席"],
    hid=["躺下背不着床"],
    definition="卧时背不着席。痉病之候。",
    note="金匮要略·痉湿暍病：'卧不着席，脚挛急，必齘齿，可与大承气汤。'")
SYN["Xiechi"] = dict(
    alt=["齘齿"],
    hid=["磨牙", "咬牙"],
    definition="牙齿相磨。痉病之候。",
    note="金匮要略·痉湿暍病。")

# ========== 十六、痰饮类 ==========
SYN["Shuizouchangjianliliyousheng"] = dict(
    alt=["水走肠间沥沥有声"],
    hid=["肚子里水响"],
    definition="水走肠间沥沥有声。痰饮之候。",
    note="金匮要略·痰饮：'水走肠间，沥沥有声，谓之痰饮。'")
SYN["Tanduo"] = dict(
    alt=["痰多"],
    hid=["痰多", "痰多黏", "老有痰", "有痰"],
    definition="痰涎多。",
    note="")
SYN["Tanduoqingxi"] = dict(
    alt=["痰多清稀"],
    hid=["痰稀白", "痰清稀"],
    definition="痰多而清稀。寒饮之候。",
    note="")

# ========== 十七、水气类 ==========
SYN["Shuizhong"] = dict(
    alt=["水肿", "水气", "浮肿"],
    hid=["浮肿", "水肿", "身上肿", "肿了"],
    definition="体内水液潴留，泛溢肌肤。",
    note="金匮要略·水气病：'师曰：病有风水、有皮水、有正水、有石水、有黄汗。'")
SYN["Yishenxizhong"] = dict(
    alt=["一身悉肿"],
    hid=["全身都肿"],
    definition="全身尽肿。",
    note="金匮要略·水气病：'风水恶风，一身悉肿，脉浮不渴，续自汗出，无大热，越婢汤主之。'")
SYN["Yishenmianmuhuangzhong"] = dict(
    alt=["一身面目黄肿"],
    hid=["全身面目黄肿"],
    definition="全身面目黄肿。",
    note="金匮要略·水气病。")
SYN["Xingzhong"] = dict(
    alt=["形肿"],
    hid=["形体浮肿"],
    definition="形体浮肿。",
    note="金匮要略·痰饮：'其形如肿，谓之支饮。'")
SYN["Fuzhonganzhimeizhi"] = dict(
    alt=["胕肿按之没指"],
    hid=["按下去一个坑"],
    definition="浮肿按之凹陷没指。",
    note="金匮要略·水气病：'皮水其脉亦浮，外证胕肿，按之没指，不恶风，其腹如鼓，不渴，当发其汗。'")
SYN["Pishui"] = dict(
    alt=["皮水"],
    hid=["皮水"],
    definition="皮水，水在皮肤。",
    note="金匮要略·水气病：'皮水为病，四肢肿，水气在皮肤中，四肢聂聂动者，防己茯苓汤主之。'")
SYN["Lishui"] = dict(
    alt=["里水"],
    hid=["里水"],
    definition="里水，水在里。",
    note="金匮要略·水气病：'里水者，一身面目黄肿，其脉沉，小便不利，故令病水。'")

# ========== 十八、黄疸类 ==========
SYN["Huangdan"] = dict(
    alt=["黄疸"],
    hid=["黄疸", "全身发黄", "眼睛黄"],
    definition="身黄、目黄、小便黄之病。湿热或寒湿所致。",
    note="金匮要略·黄疸病：'黄家所得，从湿得之。'")
SYN["Jiuhuangdan"] = dict(
    alt=["酒黄疸"],
    hid=["喝酒引起的黄疸"],
    definition="因饮酒所致之黄疸。",
    note="金匮要略·黄疸病：'酒黄疸，心中懊憹或热痛，栀子大黄汤主之。'")
SYN["Nvlaodan"] = dict(
    alt=["女劳疸"],
    hid=["房劳引起的黄疸"],
    definition="因房劳所致之黄疸，额上黑。",
    note="金匮要略·黄疸病：'额上黑，微汗出，手足中热，薄暮即发，膀胱急，小便自利，名曰女劳疸。'")
SYN["Hanzhanyi"] = dict(
    alt=["汗沾衣"],
    hid=["汗把衣服染黄"],
    definition="汗出沾衣色黄。黄汗之候。",
    note="金匮要略·水气病。")
SYN["Sezhenghuangrubaizhi"] = dict(
    alt=["色正黄如柏汁"],
    hid=["汗色黄如柏汁"],
    definition="汗色正黄如柏汁。黄汗之候。",
    note="金匮要略·水气病。")
SYN["Shenseruxunhuang"] = dict(
    alt=["身色如熏黄"],
    hid=["身上黄得像熏过"],
    definition="身色如熏黄而晦暗。寒湿黄疸之候。",
    note="金匮要略·黄疸病：'黄家日晡所发热，而反恶寒，此为女劳得之。'")

# ========== 十九、血证类 ==========
SYN["Nvxue"] = dict(
    alt=["衄血", "鼻衄"],
    hid=["流鼻血", "鼻子出血"],
    definition="鼻中出血。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病：'衄家不可发汗。'")
SYN["Xiaxue"] = dict(
    alt=["下血"],
    hid=["便血", "阴道出血"],
    definition="前后二阴下血。",
    note="金匮要略·惊悸吐衄下血胸满瘀血病。")
SYN["Louxia"] = dict(
    alt=["漏下"],
    hid=["月经淋漓不断", "阴道淋漓出血"],
    definition="妇人经血淋漓不断。",
    note="金匮要略·妇人杂病：'妇人宿有癥病，经断未及三月，而得漏下不止。'")
SYN["Banchanhouxiaxuebuduan"] = dict(
    alt=["半产后下血不断"],
    hid=["小产后出血不止"],
    definition="半产后下血不止。",
    note="金匮要略·妇人妊娠病。")

# ========== 二十、虚劳类 ==========
SYN["Xulao"] = dict(
    alt=["虚劳"],
    hid=["虚劳", "身体虚"],
    definition="脏腑虚损、气血不足之慢性病。",
    note="金匮要略·血痹虚劳：'夫男子平人，脉大为劳，极虚亦为劳。'")
SYN["Xulaoyaotong"] = dict(
    alt=["虚劳腰痛"],
    hid=["虚劳腰疼"],
    definition="虚劳而腰痛。",
    note="金匮要略·血痹虚劳：'虚劳腰痛，少腹拘急，小便不利者，八味肾气丸主之。'")
SYN["Xulaoxufanbudemian"] = dict(
    alt=["虚劳虚烦不得眠"],
    hid=["虚劳失眠心烦"],
    definition="虚劳虚烦不得眠。",
    note="金匮要略·血痹虚劳：'虚劳虚烦不得眠，酸枣仁汤主之。'")
SYN["Wulaoxuji"] = dict(
    alt=["五劳虚极"],
    hid=["五劳虚到极点"],
    definition="五劳虚极羸瘦。",
    note="金匮要略·血痹虚劳：'五劳虚极羸瘦，腹满不能饮食……缓中补虚，大黄蟅虫丸主之。'")
SYN["Xulei"] = dict(
    alt=["虚羸"],
    hid=["身体虚弱消瘦"],
    definition="虚弱羸瘦。",
    note="金匮要略·血痹虚劳。")
SYN["Xuleishaoqi"] = dict(
    alt=["虚羸少气"],
    hid=["虚弱气短"],
    definition="虚羸而少气。",
    note="金匮要略·肺痿肺痈咳嗽上气：'火逆上气，咽喉不利……麦门冬汤主之。'")
SYN["Yijing"] = dict(
    alt=["遗精"],
    hid=["遗精", "滑精"],
    definition="精液不自主遗出。",
    note="金匮要略·血痹虚劳：'夫失精家，少腹弦急，阴头寒。'")
SYN["Faluo"] = dict(
    alt=["发落"],
    hid=["掉头发", "脱发"],
    definition="头发脱落。",
    note="金匮要略·血痹虚劳。")
SYN["Mengshijing"] = dict(
    alt=["梦失精"],
    hid=["做梦遗精"],
    definition="梦中失精。",
    note="金匮要略·血痹虚劳。")
SYN["Shijingjia"] = dict(
    alt=["失精家"],
    hid=["经常遗精的人"],
    definition="素患失精之人。",
    note="金匮要略·血痹虚劳：'夫失精家，少腹弦急，阴头寒，目眩，发落……桂枝加龙骨牡蛎汤主之。'")
SYN["Feiweituxianmo"] = dict(
    alt=["肺痿吐涎沫"],
    hid=["肺痿吐白沫"],
    definition="肺痿而吐涎沫。",
    note="金匮要略·肺痿肺痈咳嗽上气：'肺痿吐涎沫而不咳者，其人不渴，必遗尿，小便数……甘草干姜汤主之。'")
SYN["Feitong"] = dict(
    alt=["肺痛"],
    hid=["肺痛"],
    definition="肺部疼痛。",
    note="")
SYN["Fanman"] = dict(
    alt=["烦满"],
    hid=["心烦胀满"],
    definition="心烦而满。",
    note="")

# ========== 二十一、妇人妊娠产后类 ==========
SYN["Renshen"] = dict(
    alt=["妊娠"],
    hid=["怀孕", "有了"],
    definition="妊娠。",
    note="金匮要略·妇人妊娠病。")
SYN["Renshenxiaxue"] = dict(
    alt=["妊娠下血"],
    hid=["怀孕出血"],
    definition="妊娠期间下血。",
    note="金匮要略·妇人妊娠病：'妇人怀娠六七月，脉弦发热……当以附子汤温其脏。'")
SYN["Renshenoutubuzhi"] = dict(
    alt=["妊娠呕吐不止"],
    hid=["怀孕吐个不停"],
    definition="妊娠呕吐不止。",
    note="金匮要略·妇人妊娠病：'妊娠呕吐不止，干姜人参半夏丸主之。'")
SYN["Renshenyoushuiqi"] = dict(
    alt=["妊娠有水气"],
    hid=["怀孕水肿"],
    definition="妊娠有水气。",
    note="金匮要略·妇人妊娠病：'妊娠有水气，身重，小便不利，洒淅恶寒，起即头眩，葵子茯苓散主之。'")
SYN["Furensuyouzhengbing"] = dict(
    alt=["妇人宿有癥病"],
    hid=["妇人原有癥病"],
    definition="妇人素有癥病。",
    note="金匮要略·妇人妊娠病：'妇人宿有癥病，经断未及三月，而得漏下不止。'")
SYN["Jingduan"] = dict(
    alt=["经断"],
    hid=["月经停了", "闭经"],
    definition="月经停止。",
    note="金匮要略·妇人杂病。")
SYN["Jingduanweijisanyue"] = dict(
    alt=["经断未及三月"],
    hid=["停经不到三个月"],
    definition="经断未及三月。",
    note="金匮要略·妇人妊娠病。")
SYN["Jingshuibuli"] = dict(
    alt=["经水不利"],
    hid=["月经不畅", "月经不调"],
    definition="月经不畅利。",
    note="金匮要略·妇人杂病：'妇人经水不利下，抵当汤主之。'")
SYN["Jingyiyuezaijian"] = dict(
    alt=["经一月再见"],
    hid=["一个月来两次月经"],
    definition="月经一月两至。",
    note="金匮要略·妇人杂病。")
SYN["Jingshuishilai"] = dict(
    alt=["经水适来"],
    hid=["月经刚来"],
    definition="月经适来。",
    note="伤寒论第143条：'妇人中风，七八日续得寒热，发作有时，经水适断者，此为热入血室。'")
SYN["Jingshuishiduan"] = dict(
    alt=["经水适断"],
    hid=["月经刚断"],
    definition="月经适断。",
    note="伤寒论第143条。")
SYN["Daixia"] = dict(
    alt=["带下"],
    hid=["白带", "带下多"],
    definition="妇人带下病。",
    note="金匮要略·妇人杂病：'妇人带下，经水不利，少腹满痛。'")
SYN["Taidong"] = dict(
    alt=["胎动"],
    hid=["胎动", "胎动不安"],
    definition="胎动不安。",
    note="金匮要略·妇人妊娠病：'妊娠养胎，白术散主之。'")
SYN["Taidongzaiqishang"] = dict(
    alt=["胎动在脐上"],
    hid=["胎动在肚脐上"],
    definition="胎动在脐上。",
    note="金匮要略·妇人妊娠病。")
SYN["Chanhoufutong"] = dict(
    alt=["产后腹痛"],
    hid=["产后肚子疼"],
    definition="产后腹痛。",
    note="金匮要略·妇人产后病：'产后腹中㽲痛，当归生姜羊肉汤主之。'")
SYN["Banchan"] = dict(
    alt=["半产"],
    hid=["小产", "流产"],
    definition="半产，即小产。",
    note="金匮要略·妇人妊娠病。")
SYN["Chanhouxiali"] = dict(
    alt=["产后下利"],
    hid=["产后拉肚子"],
    definition="产后下利。",
    note="金匮要略·妇人产后病：'产后下利虚极，白头翁加甘草阿胶汤主之。'")
SYN["Furenyinhan"] = dict(
    alt=["妇人阴寒"],
    hid=["妇人阴部寒冷"],
    definition="妇人阴中寒冷。",
    note="金匮要略·妇人杂病：'妇人阴寒，温阴中坐药，蛇床子散主之。'")
SYN["Furenshaofuman"] = dict(
    alt=["妇人少腹满"],
    hid=["妇人小腹胀满"],
    definition="妇人少腹满。",
    note="金匮要略·妇人杂病。")
SYN["Furenshaofumanrudunzhuang"] = dict(
    alt=["妇人少腹满如敦状"],
    hid=["妇人小腹胀如敦"],
    definition="妇人少腹满如敦状。",
    note="金匮要略·妇人杂病：'妇人少腹满如敦状，小便微难而不渴，生后者，此为水与血俱结在血室也。'")
SYN["Furenzangzao"] = dict(
    alt=["妇人脏躁", "脏躁"],
    hid=["脏躁", "无故悲伤想哭"],
    definition="妇人脏躁，喜悲伤欲哭。",
    note="金匮要略·妇人杂病：'妇人脏躁，喜悲伤欲哭，象如神灵所作，数欠伸，甘麦大枣汤主之。'")
SYN["Shaofumantong"] = dict(
    alt=["少腹满痛"],
    hid=["小腹又胀又痛"],
    definition="少腹满痛。",
    note="金匮要略·妇人杂病。")

# ========== 二十二、前阴类 ==========
SYN["Yinyang"] = dict(
    alt=["阴痒"],
    hid=["阴部瘙痒", "外阴痒"],
    definition="前阴瘙痒。",
    note="金匮要略·妇人杂病。")
SYN["Yinzhong"] = dict(
    alt=["阴肿"],
    hid=["阴部肿"],
    definition="前阴肿胀。",
    note="")
SYN["Yinzhongtong"] = dict(
    alt=["阴中痛"],
    hid=["阴部疼痛"],
    definition="阴中疼痛。",
    note="")
SYN["Yinchui"] = dict(
    alt=["阴吹"],
    hid=["阴道排气"],
    definition="阴中排气有声。",
    note="金匮要略·妇人杂病：'胃气下泄，阴吹而正喧，此谷气之实也，膏发煎导之。'")
SYN["Yintouhan"] = dict(
    alt=["阴头寒"],
    hid=["龟头发冷"],
    definition="阴头寒冷。",
    note="金匮要略·血痹虚劳：'夫失精家，少腹弦急，阴头寒。'")
SYN["Yinchuang"] = dict(
    alt=["阴疮"],
    hid=["阴部生疮"],
    definition="前阴生疮。",
    note="")
SYN["Yinzhongjishengchuang"] = dict(
    alt=["阴中即生疮"],
    hid=["阴中立刻生疮"],
    definition="阴中即生疮。",
    note="金匮要略·妇人杂病。")
SYN["Yinzhongshichuanglanzhe"] = dict(
    alt=["阴中蚀疮烂者"],
    hid=["阴中蚀烂"],
    definition="阴中蚀疮溃烂。",
    note="金匮要略·妇人杂病：'少阴脉滑而数者，阴中即生疮，阴中蚀疮烂者，狼牙汤洗之。'")
SYN["Yinzhongshichuang"] = dict(
    alt=["阴中蚀疮"],
    hid=["阴中蚀烂生疮"],
    definition="阴中蚀疮。",
    note="金匮要略·妇人杂病。")
SYN["Nangsuo"] = dict(
    alt=["囊缩"],
    hid=["阴囊收缩"],
    definition="阴囊收缩。",
    note="伤寒论第6条。")
SYN["Yinchetong"] = dict(
    alt=["阴掣痛"],
    hid=["阴部抽掣痛"],
    definition="阴部掣痛。",
    note="")
SYN["Yinxiashi"] = dict(
    alt=["阴下湿"],
    hid=["阴部潮湿"],
    definition="前阴潮湿。",
    note="")
SYN["Yinhushan"] = dict(
    alt=["阴狐疝"],
    hid=["狐疝", "小肠气"],
    definition="阴狐疝，阴囊时大时小。",
    note="金匮要略·趺蹶手指臂肿转筋阴狐疝蛔虫病：'阴狐疝气者，偏有小大，时时上下，蜘蛛散主之。'")
SYN["Pianyouxiaoda"] = dict(
    alt=["偏有小大"],
    hid=["一侧大一侧小"],
    definition="阴囊偏有大小。",
    note="金匮要略·趺蹶手指臂肿转筋阴狐疝蛔虫病。")
SYN["Shishishangxia"] = dict(
    alt=["时时上下"],
    hid=["时上时下"],
    definition="时上时下。",
    note="金匮要略·趺蹶手指臂肿转筋阴狐疝蛔虫病。")

# ========== 二十三、疮疡痈类 ==========
SYN["Shenyouchuang"] = dict(
    alt=["身有疮"],
    hid=["身上生疮"],
    definition="身体生疮。",
    note="金匮要略·疮痈肠痈浸淫病。")
SYN["Younong"] = dict(
    alt=["有脓"],
    hid=["有脓"],
    definition="疮痈有脓。",
    note="金匮要略·疮痈肠痈浸淫病：'诸痈肿，欲知有脓无脓，以手掩肿上，热者为有脓。'")
SYN["Feiyong"] = dict(
    alt=["肺痈"],
    hid=["肺痈", "咳吐脓血"],
    definition="肺痈，热毒壅肺、咳吐脓血。",
    note="金匮要略·肺痿肺痈咳嗽上气：'咳而胸满，振寒脉数，咽干不渴，时出浊唾腥臭，久久吐脓如米粥者，为肺痈，桔梗汤主之。'")
SYN["Changyong"] = dict(
    alt=["肠痈"],
    hid=["肠痈", "阑尾脓肿"],
    definition="肠痈，热毒瘀结肠腑。",
    note="金匮要略·疮痈肠痈浸淫病：'肠痈者，少腹肿痞，按之即痛如淋，小便自调，时时发热，自汗出，复恶寒……大黄牡丹汤主之。'")
SYN["Nvemu"] = dict(
    alt=["疟母"],
    hid=["疟疾后痞块"],
    definition="疟母，疟久结为癥瘕。",
    note="金匮要略·疟病：'病疟以月一日发，当以十五日愈……此结为癥瘕，名曰疟母，急治之，宜鳖甲煎丸。'")

# ========== 二十四、结胸、肝着等 ==========
SYN["Jiexiong"] = dict(
    alt=["结胸"],
    hid=["结胸", "胸脘硬痛拒按"],
    definition="邪结胸中，心下硬痛。",
    note="伤寒论第128条：'问曰：病有结胸，有脏结，其状何如？答曰：按之痛，寸脉浮，关脉沉，名曰结胸也。'")
SYN["Hanshijiexiong"] = dict(
    alt=["寒实结胸"],
    hid=["寒实结胸"],
    definition="寒实结胸，无热证。",
    note="伤寒论第141条：'寒实结胸，无热证者，与三物小陷胸汤……白散亦可服。'")
SYN["Ganzhe"] = dict(
    alt=["肝着"],
    hid=["肝着", "想捶胸口"],
    definition="肝着，胸胁痞闷，常欲蹈其胸上。",
    note="金匮要略·五脏风寒积聚病：'肝着，其人常欲蹈其胸上，先未苦时，但欲饮热，旋覆花汤主之。'")
SYN["Changyudaqixiongshang"] = dict(
    alt=["常欲蹈其胸上"],
    hid=["老想捶胸口"],
    definition="常欲蹈其胸上。肝着之候。",
    note="金匮要略·五脏风寒积聚病。")
SYN["Changyudaoqixiongshang"] = dict(
    alt=["常欲蹈其胸上"],
    hid=["老想捶胸口"],
    definition="常欲蹈其胸上。肝着之候。",
    note="金匮要略·五脏风寒积聚病。")
SYN["Citong"] = dict(
    alt=["刺痛"],
    hid=["刺痛", "针扎一样疼"],
    definition="疼痛如针刺。瘀血之候。",
    note="胡老：刺痛不移为瘀血之征。")
SYN["Neiyoujiuhan"] = dict(
    alt=["内有久寒"],
    hid=["体内有陈寒"],
    definition="内有久寒。",
    note="金匮要略·妇人杂病：'妇人少腹寒，久不受胎……温经汤主之。'")
# 寒疝绕脐痛（《金匮要略·腹满寒疝宿食》大乌头煎证）：本体仅保留规范基名
# Hanshanraoqitong（「脐」qí）。此前的 Hanshanraogitong 系拼写讹误（gi ↔ qi），
# 其 ABox 个体已更名为 Hanshanraoqitong_instance，故此处不再保留重复 SYN 条目。
SYN["Jiaoqichongxin"] = dict(
    alt=["脚气冲心"],
    hid=["脚气冲心"],
    definition="脚气冲心，气逆上冲。",
    note="金匮要略·中风历节病。")
