# Java 环境配置
JAVA_HOME=C:\Program Files\Java\jdk-26.0.1

#MySQL环境
MYSQL_SRV_NAME=MySQL80

# Ontop CLI 安装根目录
ONTOP_HOME=D:\work\Ontology\ontop-cli-5.5.0

# Camunda 安装根目录
CAMUNDA_HOME=D:\work\Ontology\c8run-8.9.6

# RabbitMQ 安装根目录
RABBITMQ_HOME=D:\work\Ontology\rabbitmq_server-4.3.4

##########中医运行环境#################################
#### ★ 新增：Ontop 属性文件绝对路径
ONTOP_PROPERTIES=D:\work\Ontology\TraditionalChineseMedicineOntology\ontology\database\tcm.properties
#### ★ 新增：OBDA 映射文件绝对路径
ONTOP_MAPPING=D:\work\Ontology\TraditionalChineseMedicineOntology\ontology\database\tcm.obda
#### ★ 新增：本体主文件绝对路径
ONTOLOGY_FILE=D:\work\Ontology\TraditionalChineseMedicineOntology\ontology\TCM.owl
ONTOLOGY_CATALOG=D:\work\Ontology\TraditionalChineseMedicineOntology\ontology\catalog-v001.xml

##########pizza环境#################################
#### ★ 新增：Ontop 属性文件绝对路径
#ONTOP_PROPERTIES=D:\work\Ontology\pizza-ontology\ontology\database\myPizza.properties
#### ★ 新增：OBDA 映射文件绝对路径
#ONTOP_MAPPING=D:\work\Ontology\pizza-ontology\ontology\database\myPizza.obda
#### ★ 新增：本体主文件绝对路径
#ONTOLOGY_FILE=D:\work\Ontology\pizza-ontology\ontology\pizza-all-classes.owl
#ONTOLOGY_CATALOG=D:\work\Ontology\pizza-ontology\ontology\catalog-v001.xml