# Java 环境配置
JAVA_HOME=C:\Program Files\Java\jdk-26.0.1

# 本体主文件绝对路径
ONTOLOGY_FILE=D:\work\Ontology\pizza-ontology\ontology\pizza-all-classes.owl

# 数据库 mapping 文件所在目录
MAPPING_DIR=D:\work\Ontology\pizza-ontology\ontology\database

# Ontop CLI 安装根目录
ONTOP_HOME=D:\work\Ontology\ontop-cli-5.5.0

# Camunda 安装根目录
CAMUNDA_HOME=D:\work\Ontology\c8run-8.9.6

# RabbitMQ 安装根目录
RABBITMQ_HOME=D:\work\Ontology\rabbitmq_server-4.3.4